#!/usr/bin/env python3
"""Write seo-pages/data/parks.jsonl from locked Wikipedia NP dates.

Primary date for every row is Wikipedia’s “Date established as park”
column on List of national parks of the United States — the day Congress
(or the establishing act) made the unit a National Park.

That is not the first monument, reservation, lakeshore, river, memorial,
or authorization date. NPS Park Anniversaries often lists those earlier
first-unit dates; they are stored as footnotes only and never mapped.

Do not invent dates. If a day is not on the Wikipedia list column, it
does not belong in established_date.
"""

from __future__ import annotations

import json
from pathlib import Path

OUT = Path(__file__).resolve().parents[1] / "data" / "parks.jsonl"

WIKIPEDIA_LIST = "List of national parks of the United States"
WIKIPEDIA_LIST_URL = (
    "https://en.wikipedia.org/wiki/List_of_national_parks_of_the_United_States"
)
WIKIPEDIA_COLUMN = "Date established as park"
NPS_ANNIVERSARIES_URL = (
    "https://www.nps.gov/subjects/npscelebrates/park-anniversaries.htm"
)
NPS_ANNIVERSARIES_RETRIEVED = "2026-09-06"
WIKIPEDIA_RETRIEVED = "2026-09-06"

# slug, name, official_name, iso, locations, wikipedia_title, prior, date_note
# prior: None | (kind, iso, label) from NPS Park Anniversaries first-unit row
#        when that first-unit day differs from the Wikipedia NP date.
PARKS: list[tuple] = [
    (
        "yellowstone",
        "Yellowstone",
        "Yellowstone National Park",
        "1872-03-01",
        ("Wyoming", "Montana", "Idaho"),
        "Yellowstone National Park",
        None,
        None,
    ),
    (
        "sequoia",
        "Sequoia",
        "Sequoia National Park",
        "1890-09-25",
        ("California",),
        "Sequoia National Park",
        None,
        None,
    ),
    (
        "yosemite",
        "Yosemite",
        "Yosemite National Park",
        "1890-10-01",
        ("California",),
        "Yosemite National Park",
        None,
        None,
    ),
    (
        "mount-rainier",
        "Mount Rainier",
        "Mount Rainier National Park",
        "1899-03-02",
        ("Washington",),
        "Mount Rainier National Park",
        None,
        None,
    ),
    (
        "crater-lake",
        "Crater Lake",
        "Crater Lake National Park",
        "1902-05-22",
        ("Oregon",),
        "Crater Lake National Park",
        None,
        None,
    ),
    (
        "wind-cave",
        "Wind Cave",
        "Wind Cave National Park",
        "1903-01-09",
        ("South Dakota",),
        "Wind Cave National Park",
        None,
        None,
    ),
    (
        "mesa-verde",
        "Mesa Verde",
        "Mesa Verde National Park",
        "1906-06-29",
        ("Colorado",),
        "Mesa Verde National Park",
        None,
        None,
    ),
    (
        "glacier",
        "Glacier",
        "Glacier National Park",
        "1910-05-11",
        ("Montana",),
        "Glacier National Park (U.S.)",
        None,
        None,
    ),
    (
        "rocky-mountain",
        "Rocky Mountain",
        "Rocky Mountain National Park",
        "1915-01-26",
        ("Colorado",),
        "Rocky Mountain National Park",
        None,
        None,
    ),
    (
        "hawaii-volcanoes",
        "Hawaiʻi Volcanoes",
        "Hawaiʻi Volcanoes National Park",
        "1916-08-01",
        ("Hawaii",),
        "Hawaiʻi Volcanoes National Park",
        None,
        "Established as Hawaii National Park. Haleakalā later became its own National Park (1961-07-01).",
    ),
    (
        "lassen-volcanic",
        "Lassen Volcanic",
        "Lassen Volcanic National Park",
        "1916-08-09",
        ("California",),
        "Lassen Volcanic National Park",
        (
            "national_monument",
            "1907-05-06",
            "Cinder Cone and Lassen Peak national monuments",
        ),
        "Wikipedia maps the National Park date August 9, 1916. NPS Park Anniversaries lists May 6, 1907 for the earlier monuments, later incorporated.",
    ),
    (
        "denali",
        "Denali",
        "Denali National Park",
        "1917-02-26",
        ("Alaska",),
        "Denali National Park and Preserve",
        None,
        "Established as Mount McKinley National Park. ANILCA (December 2, 1980) renamed and expanded the unit; the National Park date stays February 26, 1917.",
    ),
    (
        "acadia",
        "Acadia",
        "Acadia National Park",
        "1919-02-26",
        ("Maine",),
        "Acadia National Park",
        ("national_monument", "1916-07-08", "Sieur de Monts National Monument"),
        "Redesignated Lafayette National Park on February 26, 1919; later renamed Acadia. The mapped date is the National Park day, not the 1916 monument.",
    ),
    (
        "grand-canyon",
        "Grand Canyon",
        "Grand Canyon National Park",
        "1919-02-26",
        ("Arizona",),
        "Grand Canyon National Park",
        ("national_monument", "1908", "Grand Canyon National Monument"),
        "Wikipedia and NPS both use February 26, 1919 as the National Park date. NPS Park Anniversaries notes the 1908 monument without a day; that year is not mapped.",
    ),
    (
        "zion",
        "Zion",
        "Zion National Park",
        "1919-11-19",
        ("Utah",),
        "Zion National Park",
        ("national_monument", "1909-07-31", "Mukuntuweap National Monument"),
        None,
    ),
    (
        "hot-springs",
        "Hot Springs",
        "Hot Springs National Park",
        "1921-03-04",
        ("Arkansas",),
        "Hot Springs National Park",
        ("reservation", "1832-04-20", "Hot Springs Reservation"),
        "Wikipedia notes the 1832 federal reserve. The birth card uses the National Park redesignation date March 4, 1921.",
    ),
    (
        "bryce-canyon",
        "Bryce Canyon",
        "Bryce Canyon National Park",
        "1928-02-25",
        ("Utah",),
        "Bryce Canyon National Park",
        ("national_monument", "1923-06-08", "Bryce Canyon National Monument"),
        None,
    ),
    (
        "grand-teton",
        "Grand Teton",
        "Grand Teton National Park",
        "1929-02-26",
        ("Wyoming",),
        "Grand Teton National Park",
        None,
        None,
    ),
    (
        "carlsbad-caverns",
        "Carlsbad Caverns",
        "Carlsbad Caverns National Park",
        "1930-05-14",
        ("New Mexico",),
        "Carlsbad Caverns National Park",
        ("national_monument", "1923-10-25", "Carlsbad Cave National Monument"),
        None,
    ),
    (
        "everglades",
        "Everglades",
        "Everglades National Park",
        "1934-05-30",
        ("Florida",),
        "Everglades National Park",
        None,
        None,
    ),
    (
        "great-smoky-mountains",
        "Great Smoky Mountains",
        "Great Smoky Mountains National Park",
        "1934-06-15",
        ("North Carolina", "Tennessee"),
        "Great Smoky Mountains National Park",
        ("authorization", "1926-05-22", "Great Smoky Mountains National Park (authorized)"),
        "NPS Park Anniversaries lists the 1926 authorization. Wikipedia’s established-as-park date is June 15, 1934.",
    ),
    (
        "shenandoah",
        "Shenandoah",
        "Shenandoah National Park",
        "1935-12-26",
        ("Virginia",),
        "Shenandoah National Park",
        ("authorization", "1926-05-22", "Shenandoah National Park (authorized)"),
        "NPS Park Anniversaries lists the 1926 authorization. Wikipedia’s established-as-park date is December 26, 1935.",
    ),
    (
        "olympic",
        "Olympic",
        "Olympic National Park",
        "1938-06-29",
        ("Washington",),
        "Olympic National Park",
        ("national_monument", "1909-03-02", "Mount Olympus National Monument"),
        None,
    ),
    (
        "kings-canyon",
        "Kings Canyon",
        "Kings Canyon National Park",
        "1940-03-04",
        ("California",),
        "Kings Canyon National Park",
        ("other_national_park", "1890-10-01", "General Grant National Park"),
        "Wikipedia states Kings Canyon was designated in 1940 and subsumed General Grant National Park (October 1, 1890). The mapped date is March 4, 1940.",
    ),
    (
        "isle-royale",
        "Isle Royale",
        "Isle Royale National Park",
        "1940-04-03",
        ("Michigan",),
        "Isle Royale National Park",
        ("authorization", "1931-03-03", "Isle Royale National Park (authorized)"),
        "NPS Park Anniversaries lists March 3, 1931. Wikipedia’s established-as-park date is April 3, 1940.",
    ),
    (
        "mammoth-cave",
        "Mammoth Cave",
        "Mammoth Cave National Park",
        "1941-07-01",
        ("Kentucky",),
        "Mammoth Cave National Park",
        ("authorization", "1926-05-26", "Mammoth Cave National Park (authorized)"),
        "NPS Park Anniversaries lists the 1926 authorization. Wikipedia’s established-as-park date is July 1, 1941.",
    ),
    (
        "big-bend",
        "Big Bend",
        "Big Bend National Park",
        "1944-06-12",
        ("Texas",),
        "Big Bend National Park",
        ("authorization", "1935-06-20", "Big Bend National Park (authorized)"),
        "NPS Park Anniversaries lists June 20, 1935. Wikipedia’s established-as-park date is June 12, 1944.",
    ),
    (
        "virgin-islands",
        "Virgin Islands",
        "Virgin Islands National Park",
        "1956-08-02",
        ("U.S. Virgin Islands",),
        "Virgin Islands National Park",
        None,
        None,
    ),
    (
        "haleakala",
        "Haleakalā",
        "Haleakalā National Park",
        "1961-07-01",
        ("Hawaii",),
        "Haleakalā National Park",
        ("other_national_park", "1916-08-01", "Hawaii National Park"),
        "Detached from Hawaii National Park. Wikipedia’s established-as-park date for Haleakalā is July 1, 1961, not the 1916 Hawaii National Park date.",
    ),
    (
        "petrified-forest",
        "Petrified Forest",
        "Petrified Forest National Park",
        "1962-12-09",
        ("Arizona",),
        "Petrified Forest National Park",
        ("national_monument", "1906-12-08", "Petrified Forest National Monument"),
        None,
    ),
    (
        "canyonlands",
        "Canyonlands",
        "Canyonlands National Park",
        "1964-09-12",
        ("Utah",),
        "Canyonlands National Park",
        None,
        None,
    ),
    (
        "north-cascades",
        "North Cascades",
        "North Cascades National Park",
        "1968-10-02",
        ("Washington",),
        "North Cascades National Park",
        None,
        None,
    ),
    (
        "redwood",
        "Redwood",
        "Redwood National Park",
        "1968-10-02",
        ("California",),
        "Redwood National and State Parks",
        None,
        None,
    ),
    (
        "arches",
        "Arches",
        "Arches National Park",
        "1971-11-12",
        ("Utah",),
        "Arches National Park",
        ("national_monument", "1929-04-12", "Arches National Monument"),
        "NPS Park Anniversaries lists the 1929 monument (and a later redesignation note). Wikipedia’s established-as-park date is November 12, 1971.",
    ),
    (
        "capitol-reef",
        "Capitol Reef",
        "Capitol Reef National Park",
        "1971-12-18",
        ("Utah",),
        "Capitol Reef National Park",
        ("national_monument", "1937-08-02", "Capitol Reef National Monument"),
        None,
    ),
    (
        "guadalupe-mountains",
        "Guadalupe Mountains",
        "Guadalupe Mountains National Park",
        "1972-09-30",
        ("Texas",),
        "Guadalupe Mountains National Park",
        ("authorization", "1966-10-15", "Guadalupe Mountains National Park (authorized)"),
        "NPS Park Anniversaries lists October 15, 1966. Wikipedia’s established-as-park date is September 30, 1972.",
    ),
    (
        "voyageurs",
        "Voyageurs",
        "Voyageurs National Park",
        "1975-04-08",
        ("Minnesota",),
        "Voyageurs National Park",
        ("authorization", "1971-01-08", "Voyageurs National Park (authorized)"),
        "NPS Park Anniversaries lists January 8, 1971. Wikipedia’s established-as-park date is April 8, 1975.",
    ),
    (
        "badlands",
        "Badlands",
        "Badlands National Park",
        "1978-11-10",
        ("South Dakota",),
        "Badlands National Park",
        ("national_monument", "1939-01-25", "Badlands National Monument"),
        None,
    ),
    (
        "theodore-roosevelt",
        "Theodore Roosevelt",
        "Theodore Roosevelt National Park",
        "1978-11-10",
        ("North Dakota",),
        "Theodore Roosevelt National Park",
        ("memorial", "1947-04-25", "Theodore Roosevelt National Memorial Park"),
        None,
    ),
    (
        "channel-islands",
        "Channel Islands",
        "Channel Islands National Park",
        "1980-03-05",
        ("California",),
        "Channel Islands National Park",
        ("national_monument", "1938-04-26", "Channel Islands National Monument"),
        None,
    ),
    (
        "biscayne",
        "Biscayne",
        "Biscayne National Park",
        "1980-06-28",
        ("Florida",),
        "Biscayne National Park",
        ("national_monument", "1968-10-18", "Biscayne National Monument"),
        None,
    ),
    (
        "gates-of-the-arctic",
        "Gates of the Arctic",
        "Gates of the Arctic National Park",
        "1980-12-02",
        ("Alaska",),
        "Gates of the Arctic National Park and Preserve",
        ("national_monument", "1978-12-01", "Gates of the Arctic National Monument"),
        "ANILCA National Park date December 2, 1980. NPS Park Anniversaries lists the December 1, 1978 monument.",
    ),
    (
        "glacier-bay",
        "Glacier Bay",
        "Glacier Bay National Park",
        "1980-12-02",
        ("Alaska",),
        "Glacier Bay National Park and Preserve",
        ("national_monument", "1925-02-26", "Glacier Bay National Monument"),
        "ANILCA National Park date December 2, 1980, not the 1925 monument.",
    ),
    (
        "katmai",
        "Katmai",
        "Katmai National Park",
        "1980-12-02",
        ("Alaska",),
        "Katmai National Park and Preserve",
        ("national_monument", "1918-09-24", "Katmai National Monument"),
        "ANILCA National Park date December 2, 1980, not the 1918 monument.",
    ),
    (
        "kenai-fjords",
        "Kenai Fjords",
        "Kenai Fjords National Park",
        "1980-12-02",
        ("Alaska",),
        "Kenai Fjords National Park",
        ("national_monument", "1978-12-01", "Kenai Fjords National Monument"),
        "ANILCA National Park date December 2, 1980.",
    ),
    (
        "kobuk-valley",
        "Kobuk Valley",
        "Kobuk Valley National Park",
        "1980-12-02",
        ("Alaska",),
        "Kobuk Valley National Park",
        ("national_monument", "1978-12-01", "Kobuk Valley National Monument"),
        "ANILCA National Park date December 2, 1980.",
    ),
    (
        "lake-clark",
        "Lake Clark",
        "Lake Clark National Park",
        "1980-12-02",
        ("Alaska",),
        "Lake Clark National Park and Preserve",
        ("national_monument", "1978-12-01", "Lake Clark National Monument"),
        "ANILCA National Park date December 2, 1980.",
    ),
    (
        "wrangell-st-elias",
        "Wrangell–St. Elias",
        "Wrangell–St. Elias National Park",
        "1980-12-02",
        ("Alaska",),
        "Wrangell–St. Elias National Park and Preserve",
        ("national_monument", "1978-12-01", "Wrangell-St. Elias National Monument"),
        "ANILCA National Park date December 2, 1980.",
    ),
    (
        "great-basin",
        "Great Basin",
        "Great Basin National Park",
        "1986-10-27",
        ("Nevada",),
        "Great Basin National Park",
        ("national_monument", "1922-01-24", "Lehman Caves National Monument"),
        None,
    ),
    (
        "american-samoa",
        "American Samoa",
        "National Park of American Samoa",
        "1988-10-31",
        ("American Samoa",),
        "National Park of American Samoa",
        None,
        None,
    ),
    (
        "dry-tortugas",
        "Dry Tortugas",
        "Dry Tortugas National Park",
        "1992-10-26",
        ("Florida",),
        "Dry Tortugas National Park",
        ("national_monument", "1935", "Fort Jefferson National Monument"),
        "Wikipedia’s established-as-park date is October 26, 1992. NPS Park Anniversaries notes Fort Jefferson National Monument (1935) without a day; that year is not mapped.",
    ),
    (
        "saguaro",
        "Saguaro",
        "Saguaro National Park",
        "1994-10-14",
        ("Arizona",),
        "Saguaro National Park",
        ("national_monument", "1933-03-01", "Saguaro National Monument"),
        None,
    ),
    (
        "death-valley",
        "Death Valley",
        "Death Valley National Park",
        "1994-10-31",
        ("California", "Nevada"),
        "Death Valley National Park",
        ("national_monument", "1933-02-11", "Death Valley National Monument"),
        None,
    ),
    (
        "joshua-tree",
        "Joshua Tree",
        "Joshua Tree National Park",
        "1994-10-31",
        ("California",),
        "Joshua Tree National Park",
        ("national_monument", "1936-08-10", "Joshua Tree National Monument"),
        None,
    ),
    (
        "black-canyon-of-the-gunnison",
        "Black Canyon of the Gunnison",
        "Black Canyon of the Gunnison National Park",
        "1999-10-21",
        ("Colorado",),
        "Black Canyon of the Gunnison National Park",
        ("national_monument", "1933-03-02", "Black Canyon of the Gunnison National Monument"),
        None,
    ),
    (
        "cuyahoga-valley",
        "Cuyahoga Valley",
        "Cuyahoga Valley National Park",
        "2000-10-11",
        ("Ohio",),
        "Cuyahoga Valley National Park",
        ("national_recreation_area", "1975-06-26", "Cuyahoga Valley National Recreation Area"),
        None,
    ),
    (
        "congaree",
        "Congaree",
        "Congaree National Park",
        "2003-11-10",
        ("South Carolina",),
        "Congaree National Park",
        ("national_monument", "1976-10-18", "Congaree Swamp National Monument"),
        None,
    ),
    (
        "great-sand-dunes",
        "Great Sand Dunes",
        "Great Sand Dunes National Park",
        "2004-09-24",
        ("Colorado",),
        "Great Sand Dunes National Park and Preserve",
        ("national_monument", "1932-03-17", "Great Sand Dunes National Monument"),
        None,
    ),
    (
        "pinnacles",
        "Pinnacles",
        "Pinnacles National Park",
        "2013-01-10",
        ("California",),
        "Pinnacles National Park",
        ("national_monument", "1908-01-16", "Pinnacles National Monument"),
        None,
    ),
    (
        "gateway-arch",
        "Gateway Arch",
        "Gateway Arch National Park",
        "2018-02-22",
        ("Missouri",),
        "Gateway Arch National Park",
        ("memorial", "1935-12-21", "Jefferson National Expansion Memorial"),
        None,
    ),
    (
        "indiana-dunes",
        "Indiana Dunes",
        "Indiana Dunes National Park",
        "2019-02-15",
        ("Indiana",),
        "Indiana Dunes National Park",
        ("national_lakeshore", "1966-11-05", "Indiana Dunes National Lakeshore"),
        None,
    ),
    (
        "white-sands",
        "White Sands",
        "White Sands National Park",
        "2019-12-20",
        ("New Mexico",),
        "White Sands National Park",
        ("national_monument", "1933-01-18", "White Sands National Monument"),
        None,
    ),
    (
        "new-river-gorge",
        "New River Gorge",
        "New River Gorge National Park and Preserve",
        "2020-12-27",
        ("West Virginia",),
        "New River Gorge National Park and Preserve",
        ("national_river", "1978-11-10", "New River Gorge National River"),
        "Newest current National Park on the Wikipedia list.",
    ),
]


def _prior_record(prior: tuple | None) -> dict | None:
    if prior is None:
        return None
    kind, raw_date, label = prior
    if len(raw_date) == 4:
        precision = "year"
    elif len(raw_date) == 10:
        precision = "day"
    else:
        raise ValueError(f"prior date must be YYYY or YYYY-MM-DD, got {raw_date}")
    return {
        "kind": kind,
        "date": raw_date,
        "date_precision": precision,
        "label": label,
        "source": "nps_park_anniversaries",
        "source_url": NPS_ANNIVERSARIES_URL,
    }


def rows() -> list[dict]:
    ordered = sorted(PARKS, key=lambda item: (item[3], item[0]))
    out: list[dict] = []
    for index, (
        slug,
        name,
        official_name,
        iso,
        locations,
        wikipedia_title,
        prior,
        date_note,
    ) in enumerate(ordered, start=1):
        out.append(
            {
                "slug": slug,
                "name": name,
                "official_name": official_name,
                "established_order": index,
                "established_date": iso,
                "date_kind": "national_park",
                "locations": list(locations),
                "wikipedia_list": WIKIPEDIA_LIST,
                "wikipedia_list_url": WIKIPEDIA_LIST_URL,
                "wikipedia_list_column": WIKIPEDIA_COLUMN,
                "wikipedia_title": wikipedia_title,
                "wikipedia_retrieved": WIKIPEDIA_RETRIEVED,
                "nps_anniversaries_url": NPS_ANNIVERSARIES_URL,
                "nps_anniversaries_retrieved": NPS_ANNIVERSARIES_RETRIEVED,
                "prior_designation": _prior_record(prior),
                "date_note": date_note,
            }
        )
    return out


def main() -> None:
    payload = rows()
    if len(payload) != 63:
        raise SystemExit(f"Expected 63 parks, built {len(payload)}")
    slugs = [row["slug"] for row in payload]
    if len(set(slugs)) != 63:
        raise SystemExit("Duplicate park slug")
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("".join(json.dumps(row, ensure_ascii=False) + "\n" for row in payload), encoding="utf-8")
    print(f"Wrote {len(payload)} parks → {OUT}")


if __name__ == "__main__":
    main()
