"""Known sitting US senator identifiers — not birth dates.

Sitting identity comes from unitedstates/congress-legislators (Bioguide /
congress.gov compiled current-member file) cross-checked against Wikipedia's
list of current United States senators (100 seats; 50 states). Dates always
come from day-precision public sources at harvest time and must agree.
Do not invent extras or days.
"""

from __future__ import annotations

WIKIPEDIA_LIST_TITLE = "List_of_current_United_States_senators"
WIKIPEDIA_LIST_URL = (
    "https://en.wikipedia.org/wiki/List_of_current_United_States_senators"
)
CONGRESS_SENATE_ROSTER_URL = (
    "https://www.congress.gov/members"
    "?q=%7B%22congress%22%3A119%2C%22chamber%22%3A%22Senate%22%7D"
)
SENATE_GOV_ROSTER_URL = "https://www.senate.gov/senators/index.htm"
LEGISLATORS_URL = (
    "https://raw.githubusercontent.com/unitedstates/congress-legislators/"
    "gh-pages/legislators-current.json"
)

POSTAL_TO_STATE: dict[str, str] = {
    "AL": "Alabama",
    "AK": "Alaska",
    "AZ": "Arizona",
    "AR": "Arkansas",
    "CA": "California",
    "CO": "Colorado",
    "CT": "Connecticut",
    "DE": "Delaware",
    "FL": "Florida",
    "GA": "Georgia",
    "HI": "Hawaii",
    "ID": "Idaho",
    "IL": "Illinois",
    "IN": "Indiana",
    "IA": "Iowa",
    "KS": "Kansas",
    "KY": "Kentucky",
    "LA": "Louisiana",
    "ME": "Maine",
    "MD": "Maryland",
    "MA": "Massachusetts",
    "MI": "Michigan",
    "MN": "Minnesota",
    "MS": "Mississippi",
    "MO": "Missouri",
    "MT": "Montana",
    "NE": "Nebraska",
    "NV": "Nevada",
    "NH": "New Hampshire",
    "NJ": "New Jersey",
    "NM": "New Mexico",
    "NY": "New York",
    "NC": "North Carolina",
    "ND": "North Dakota",
    "OH": "Ohio",
    "OK": "Oklahoma",
    "OR": "Oregon",
    "PA": "Pennsylvania",
    "RI": "Rhode Island",
    "SC": "South Carolina",
    "SD": "South Dakota",
    "TN": "Tennessee",
    "TX": "Texas",
    "UT": "Utah",
    "VT": "Vermont",
    "VA": "Virginia",
    "WA": "Washington",
    "WV": "West Virginia",
    "WI": "Wisconsin",
    "WY": "Wyoming",
}

# Alphabetical by state, then name. QIDs / Bioguide / titles are identifiers only.
SITTING_SENATORS: tuple[dict[str, str], ...] = (
    {
        "state": 'Alabama',
        "state_slug": 'alabama',
        "postal": 'AL',
        "name": 'Katie Boyd Britt',
        "last": 'Britt',
        "slug": 'katie-boyd-britt',
        "qid": 'Q111285444',
        "bioguide": 'B001319',
        "enwiki_title": 'Katie Britt',
        "senate_class": '3',
        "party": 'Republican',
    },
    {
        "state": 'Alabama',
        "state_slug": 'alabama',
        "postal": 'AL',
        "name": 'Tommy Tuberville',
        "last": 'Tuberville',
        "slug": 'tommy-tuberville',
        "qid": 'Q7819948',
        "bioguide": 'T000278',
        "enwiki_title": 'Tommy Tuberville',
        "senate_class": '2',
        "party": 'Republican',
    },
    {
        "state": 'Alaska',
        "state_slug": 'alaska',
        "postal": 'AK',
        "name": 'Dan Sullivan',
        "last": 'Sullivan',
        "slug": 'dan-sullivan',
        "qid": 'Q5218668',
        "bioguide": 'S001198',
        "enwiki_title": 'Dan Sullivan (U.S. senator)',
        "senate_class": '2',
        "party": 'Republican',
    },
    {
        "state": 'Alaska',
        "state_slug": 'alaska',
        "postal": 'AK',
        "name": 'Lisa Murkowski',
        "last": 'Murkowski',
        "slug": 'lisa-murkowski',
        "qid": 'Q22360',
        "bioguide": 'M001153',
        "enwiki_title": 'Lisa Murkowski',
        "senate_class": '3',
        "party": 'Republican',
    },
    {
        "state": 'Arizona',
        "state_slug": 'arizona',
        "postal": 'AZ',
        "name": 'Mark Kelly',
        "last": 'Kelly',
        "slug": 'mark-kelly',
        "qid": 'Q357510',
        "bioguide": 'K000377',
        "enwiki_title": 'Mark Kelly',
        "senate_class": '3',
        "party": 'Democrat',
    },
    {
        "state": 'Arizona',
        "state_slug": 'arizona',
        "postal": 'AZ',
        "name": 'Ruben Gallego',
        "last": 'Gallego',
        "slug": 'ruben-gallego',
        "qid": 'Q16218474',
        "bioguide": 'G000574',
        "enwiki_title": 'Ruben Gallego',
        "senate_class": '1',
        "party": 'Democrat',
    },
    {
        "state": 'Arkansas',
        "state_slug": 'arkansas',
        "postal": 'AR',
        "name": 'John Boozman',
        "last": 'Boozman',
        "slug": 'john-boozman',
        "qid": 'Q1344707',
        "bioguide": 'B001236',
        "enwiki_title": 'John Boozman',
        "senate_class": '3',
        "party": 'Republican',
    },
    {
        "state": 'Arkansas',
        "state_slug": 'arkansas',
        "postal": 'AR',
        "name": 'Tom Cotton',
        "last": 'Cotton',
        "slug": 'tom-cotton',
        "qid": 'Q3090307',
        "bioguide": 'C001095',
        "enwiki_title": 'Tom Cotton',
        "senate_class": '2',
        "party": 'Republican',
    },
    {
        "state": 'California',
        "state_slug": 'california',
        "postal": 'CA',
        "name": 'Adam B. Schiff',
        "last": 'Schiff',
        "slug": 'adam-b-schiff',
        "qid": 'Q350843',
        "bioguide": 'S001150',
        "enwiki_title": 'Adam Schiff',
        "senate_class": '1',
        "party": 'Democrat',
    },
    {
        "state": 'California',
        "state_slug": 'california',
        "postal": 'CA',
        "name": 'Alex Padilla',
        "last": 'Padilla',
        "slug": 'alex-padilla',
        "qid": 'Q4717593',
        "bioguide": 'P000145',
        "enwiki_title": 'Alex Padilla',
        "senate_class": '3',
        "party": 'Democrat',
    },
    {
        "state": 'Colorado',
        "state_slug": 'colorado',
        "postal": 'CO',
        "name": 'John W. Hickenlooper',
        "last": 'Hickenlooper',
        "slug": 'john-w-hickenlooper',
        "qid": 'Q430518',
        "bioguide": 'H000273',
        "enwiki_title": 'John Hickenlooper',
        "senate_class": '2',
        "party": 'Democrat',
    },
    {
        "state": 'Colorado',
        "state_slug": 'colorado',
        "postal": 'CO',
        "name": 'Michael F. Bennet',
        "last": 'Bennet',
        "slug": 'michael-f-bennet',
        "qid": 'Q554792',
        "bioguide": 'B001267',
        "enwiki_title": 'Michael Bennet',
        "senate_class": '3',
        "party": 'Democrat',
    },
    {
        "state": 'Connecticut',
        "state_slug": 'connecticut',
        "postal": 'CT',
        "name": 'Christopher Murphy',
        "last": 'Murphy',
        "slug": 'christopher-murphy',
        "qid": 'Q1077594',
        "bioguide": 'M001169',
        "enwiki_title": 'Chris Murphy',
        "senate_class": '1',
        "party": 'Democrat',
    },
    {
        "state": 'Connecticut',
        "state_slug": 'connecticut',
        "postal": 'CT',
        "name": 'Richard Blumenthal',
        "last": 'Blumenthal',
        "slug": 'richard-blumenthal',
        "qid": 'Q2023708',
        "bioguide": 'B001277',
        "enwiki_title": 'Richard Blumenthal',
        "senate_class": '3',
        "party": 'Democrat',
    },
    {
        "state": 'Delaware',
        "state_slug": 'delaware',
        "postal": 'DE',
        "name": 'Christopher A. Coons',
        "last": 'Coons',
        "slug": 'christopher-a-coons',
        "qid": 'Q923242',
        "bioguide": 'C001088',
        "enwiki_title": 'Chris Coons',
        "senate_class": '2',
        "party": 'Democrat',
    },
    {
        "state": 'Delaware',
        "state_slug": 'delaware',
        "postal": 'DE',
        "name": 'Lisa Blunt Rochester',
        "last": 'Blunt Rochester',
        "slug": 'lisa-blunt-rochester',
        "qid": 'Q26899141',
        "bioguide": 'B001303',
        "enwiki_title": 'Lisa Blunt Rochester',
        "senate_class": '1',
        "party": 'Democrat',
    },
    {
        "state": 'Florida',
        "state_slug": 'florida',
        "postal": 'FL',
        "name": 'Ashley Moody',
        "last": 'Moody',
        "slug": 'ashley-moody',
        "qid": 'Q58333626',
        "bioguide": 'M001244',
        "enwiki_title": 'Ashley Moody',
        "senate_class": '3',
        "party": 'Republican',
    },
    {
        "state": 'Florida',
        "state_slug": 'florida',
        "postal": 'FL',
        "name": 'Rick Scott',
        "last": 'Scott',
        "slug": 'rick-scott',
        "qid": 'Q439729',
        "bioguide": 'S001217',
        "enwiki_title": 'Rick Scott',
        "senate_class": '1',
        "party": 'Republican',
    },
    {
        "state": 'Georgia',
        "state_slug": 'georgia',
        "postal": 'GA',
        "name": 'Jon Ossoff',
        "last": 'Ossoff',
        "slug": 'jon-ossoff',
        "qid": 'Q28839536',
        "bioguide": 'O000174',
        "enwiki_title": 'Jon Ossoff',
        "senate_class": '2',
        "party": 'Democrat',
    },
    {
        "state": 'Georgia',
        "state_slug": 'georgia',
        "postal": 'GA',
        "name": 'Raphael G. Warnock',
        "last": 'Warnock',
        "slug": 'raphael-g-warnock',
        "qid": 'Q84146599',
        "bioguide": 'W000790',
        "enwiki_title": 'Raphael Warnock',
        "senate_class": '3',
        "party": 'Democrat',
    },
    {
        "state": 'Hawaii',
        "state_slug": 'hawaii',
        "postal": 'HI',
        "name": 'Brian Schatz',
        "last": 'Schatz',
        "slug": 'brian-schatz',
        "qid": 'Q1827902',
        "bioguide": 'S001194',
        "enwiki_title": 'Brian Schatz',
        "senate_class": '3',
        "party": 'Democrat',
    },
    {
        "state": 'Hawaii',
        "state_slug": 'hawaii',
        "postal": 'HI',
        "name": 'Mazie K. Hirono',
        "last": 'Hirono',
        "slug": 'mazie-k-hirono',
        "qid": 'Q16476',
        "bioguide": 'H001042',
        "enwiki_title": 'Mazie Hirono',
        "senate_class": '1',
        "party": 'Democrat',
    },
    {
        "state": 'Idaho',
        "state_slug": 'idaho',
        "postal": 'ID',
        "name": 'James E. Risch',
        "last": 'Risch',
        "slug": 'james-e-risch',
        "qid": 'Q721871',
        "bioguide": 'R000584',
        "enwiki_title": 'Jim Risch',
        "senate_class": '2',
        "party": 'Republican',
    },
    {
        "state": 'Idaho',
        "state_slug": 'idaho',
        "postal": 'ID',
        "name": 'Mike Crapo',
        "last": 'Crapo',
        "slug": 'mike-crapo',
        "qid": 'Q734319',
        "bioguide": 'C000880',
        "enwiki_title": 'Mike Crapo',
        "senate_class": '3',
        "party": 'Republican',
    },
    {
        "state": 'Illinois',
        "state_slug": 'illinois',
        "postal": 'IL',
        "name": 'Richard J. Durbin',
        "last": 'Durbin',
        "slug": 'richard-j-durbin',
        "qid": 'Q434804',
        "bioguide": 'D000563',
        "enwiki_title": 'Dick Durbin',
        "senate_class": '2',
        "party": 'Democrat',
    },
    {
        "state": 'Illinois',
        "state_slug": 'illinois',
        "postal": 'IL',
        "name": 'Tammy Duckworth',
        "last": 'Duckworth',
        "slug": 'tammy-duckworth',
        "qid": 'Q3036410',
        "bioguide": 'D000622',
        "enwiki_title": 'Tammy Duckworth',
        "senate_class": '3',
        "party": 'Democrat',
    },
    {
        "state": 'Indiana',
        "state_slug": 'indiana',
        "postal": 'IN',
        "name": 'Jim Banks',
        "last": 'Banks',
        "slug": 'jim-banks',
        "qid": 'Q16146788',
        "bioguide": 'B001299',
        "enwiki_title": 'Jim Banks',
        "senate_class": '1',
        "party": 'Republican',
    },
    {
        "state": 'Indiana',
        "state_slug": 'indiana',
        "postal": 'IN',
        "name": 'Todd Young',
        "last": 'Young',
        "slug": 'todd-young',
        "qid": 'Q25483',
        "bioguide": 'Y000064',
        "enwiki_title": 'Todd Young',
        "senate_class": '3',
        "party": 'Republican',
    },
    {
        "state": 'Iowa',
        "state_slug": 'iowa',
        "postal": 'IA',
        "name": 'Chuck Grassley',
        "last": 'Grassley',
        "slug": 'chuck-grassley',
        "qid": 'Q529294',
        "bioguide": 'G000386',
        "enwiki_title": 'Chuck Grassley',
        "senate_class": '3',
        "party": 'Republican',
    },
    {
        "state": 'Iowa',
        "state_slug": 'iowa',
        "postal": 'IA',
        "name": 'Joni Ernst',
        "last": 'Ernst',
        "slug": 'joni-ernst',
        "qid": 'Q13475242',
        "bioguide": 'E000295',
        "enwiki_title": 'Joni Ernst',
        "senate_class": '2',
        "party": 'Republican',
    },
    {
        "state": 'Kansas',
        "state_slug": 'kansas',
        "postal": 'KS',
        "name": 'Jerry Moran',
        "last": 'Moran',
        "slug": 'jerry-moran',
        "qid": 'Q1365787',
        "bioguide": 'M000934',
        "enwiki_title": 'Jerry Moran',
        "senate_class": '3',
        "party": 'Republican',
    },
    {
        "state": 'Kansas',
        "state_slug": 'kansas',
        "postal": 'KS',
        "name": 'Roger Marshall',
        "last": 'Marshall',
        "slug": 'roger-marshall',
        "qid": 'Q27923290',
        "bioguide": 'M001198',
        "enwiki_title": 'Roger Marshall',
        "senate_class": '2',
        "party": 'Republican',
    },
    {
        "state": 'Kentucky',
        "state_slug": 'kentucky',
        "postal": 'KY',
        "name": 'Mitch McConnell',
        "last": 'McConnell',
        "slug": 'mitch-mcconnell',
        "qid": 'Q355522',
        "bioguide": 'M000355',
        "enwiki_title": 'Mitch McConnell',
        "senate_class": '2',
        "party": 'Republican',
    },
    {
        "state": 'Kentucky',
        "state_slug": 'kentucky',
        "postal": 'KY',
        "name": 'Rand Paul',
        "last": 'Paul',
        "slug": 'rand-paul',
        "qid": 'Q463557',
        "bioguide": 'P000603',
        "enwiki_title": 'Rand Paul',
        "senate_class": '3',
        "party": 'Republican',
    },
    {
        "state": 'Louisiana',
        "state_slug": 'louisiana',
        "postal": 'LA',
        "name": 'Bill Cassidy',
        "last": 'Cassidy',
        "slug": 'bill-cassidy',
        "qid": 'Q861999',
        "bioguide": 'C001075',
        "enwiki_title": 'Bill Cassidy',
        "senate_class": '2',
        "party": 'Republican',
    },
    {
        "state": 'Louisiana',
        "state_slug": 'louisiana',
        "postal": 'LA',
        "name": 'John Kennedy',
        "last": 'Kennedy',
        "slug": 'john-kennedy',
        "qid": 'Q6250211',
        "bioguide": 'K000393',
        "enwiki_title": 'John Kennedy (Louisiana politician)',
        "senate_class": '3',
        "party": 'Republican',
    },
    {
        "state": 'Maine',
        "state_slug": 'maine',
        "postal": 'ME',
        "name": 'Angus S. King, Jr.',
        "last": 'King',
        "slug": 'angus-s-king-jr',
        "qid": 'Q544464',
        "bioguide": 'K000383',
        "enwiki_title": 'Angus King',
        "senate_class": '1',
        "party": 'Independent',
    },
    {
        "state": 'Maine',
        "state_slug": 'maine',
        "postal": 'ME',
        "name": 'Susan M. Collins',
        "last": 'Collins',
        "slug": 'susan-m-collins',
        "qid": 'Q22279',
        "bioguide": 'C001035',
        "enwiki_title": 'Susan Collins',
        "senate_class": '2',
        "party": 'Republican',
    },
    {
        "state": 'Maryland',
        "state_slug": 'maryland',
        "postal": 'MD',
        "name": 'Angela D. Alsobrooks',
        "last": 'Alsobrooks',
        "slug": 'angela-d-alsobrooks',
        "qid": 'Q58755148',
        "bioguide": 'A000382',
        "enwiki_title": 'Angela Alsobrooks',
        "senate_class": '1',
        "party": 'Democrat',
    },
    {
        "state": 'Maryland',
        "state_slug": 'maryland',
        "postal": 'MD',
        "name": 'Chris Van Hollen',
        "last": 'Van Hollen',
        "slug": 'chris-van-hollen',
        "qid": 'Q1077819',
        "bioguide": 'V000128',
        "enwiki_title": 'Chris Van Hollen',
        "senate_class": '3',
        "party": 'Democrat',
    },
    {
        "state": 'Massachusetts',
        "state_slug": 'massachusetts',
        "postal": 'MA',
        "name": 'Edward J. Markey',
        "last": 'Markey',
        "slug": 'edward-j-markey',
        "qid": 'Q1282411',
        "bioguide": 'M000133',
        "enwiki_title": 'Ed Markey',
        "senate_class": '2',
        "party": 'Democrat',
    },
    {
        "state": 'Massachusetts',
        "state_slug": 'massachusetts',
        "postal": 'MA',
        "name": 'Elizabeth Warren',
        "last": 'Warren',
        "slug": 'elizabeth-warren',
        "qid": 'Q434706',
        "bioguide": 'W000817',
        "enwiki_title": 'Elizabeth Warren',
        "senate_class": '1',
        "party": 'Democrat',
    },
    {
        "state": 'Michigan',
        "state_slug": 'michigan',
        "postal": 'MI',
        "name": 'Elissa Slotkin',
        "last": 'Slotkin',
        "slug": 'elissa-slotkin',
        "qid": 'Q30323721',
        "bioguide": 'S001208',
        "enwiki_title": 'Elissa Slotkin',
        "senate_class": '1',
        "party": 'Democrat',
    },
    {
        "state": 'Michigan',
        "state_slug": 'michigan',
        "postal": 'MI',
        "name": 'Gary C. Peters',
        "last": 'Peters',
        "slug": 'gary-c-peters',
        "qid": 'Q1494930',
        "bioguide": 'P000595',
        "enwiki_title": 'Gary Peters',
        "senate_class": '2',
        "party": 'Democrat',
    },
    {
        "state": 'Minnesota',
        "state_slug": 'minnesota',
        "postal": 'MN',
        "name": 'Amy Klobuchar',
        "last": 'Klobuchar',
        "slug": 'amy-klobuchar',
        "qid": 'Q22237',
        "bioguide": 'K000367',
        "enwiki_title": 'Amy Klobuchar',
        "senate_class": '1',
        "party": 'Democrat',
    },
    {
        "state": 'Minnesota',
        "state_slug": 'minnesota',
        "postal": 'MN',
        "name": 'Tina Smith',
        "last": 'Smith',
        "slug": 'tina-smith',
        "qid": 'Q18631509',
        "bioguide": 'S001203',
        "enwiki_title": 'Tina Smith',
        "senate_class": '2',
        "party": 'Democrat',
    },
    {
        "state": 'Mississippi',
        "state_slug": 'mississippi',
        "postal": 'MS',
        "name": 'Cindy Hyde-Smith',
        "last": 'Hyde-Smith',
        "slug": 'cindy-hyde-smith',
        "qid": 'Q5120540',
        "bioguide": 'H001079',
        "enwiki_title": 'Cindy Hyde-Smith',
        "senate_class": '2',
        "party": 'Republican',
    },
    {
        "state": 'Mississippi',
        "state_slug": 'mississippi',
        "postal": 'MS',
        "name": 'Roger F. Wicker',
        "last": 'Wicker',
        "slug": 'roger-f-wicker',
        "qid": 'Q390491',
        "bioguide": 'W000437',
        "enwiki_title": 'Roger Wicker',
        "senate_class": '1',
        "party": 'Republican',
    },
    {
        "state": 'Missouri',
        "state_slug": 'missouri',
        "postal": 'MO',
        "name": 'Eric Schmitt',
        "last": 'Schmitt',
        "slug": 'eric-schmitt',
        "qid": 'Q5387455',
        "bioguide": 'S001227',
        "enwiki_title": 'Eric Schmitt',
        "senate_class": '3',
        "party": 'Republican',
    },
    {
        "state": 'Missouri',
        "state_slug": 'missouri',
        "postal": 'MO',
        "name": 'Josh Hawley',
        "last": 'Hawley',
        "slug": 'josh-hawley',
        "qid": 'Q23020745',
        "bioguide": 'H001089',
        "enwiki_title": 'Josh Hawley',
        "senate_class": '1',
        "party": 'Republican',
    },
    {
        "state": 'Montana',
        "state_slug": 'montana',
        "postal": 'MT',
        "name": 'Steve Daines',
        "last": 'Daines',
        "slug": 'steve-daines',
        "qid": 'Q3200900',
        "bioguide": 'D000618',
        "enwiki_title": 'Steve Daines',
        "senate_class": '2',
        "party": 'Republican',
    },
    {
        "state": 'Montana',
        "state_slug": 'montana',
        "postal": 'MT',
        "name": 'Tim Sheehy',
        "last": 'Sheehy',
        "slug": 'tim-sheehy',
        "qid": 'Q124433916',
        "bioguide": 'S001232',
        "enwiki_title": 'Tim Sheehy',
        "senate_class": '1',
        "party": 'Republican',
    },
    {
        "state": 'Nebraska',
        "state_slug": 'nebraska',
        "postal": 'NE',
        "name": 'Deb Fischer',
        "last": 'Fischer',
        "slug": 'deb-fischer',
        "qid": 'Q2580649',
        "bioguide": 'F000463',
        "enwiki_title": 'Deb Fischer',
        "senate_class": '1',
        "party": 'Republican',
    },
    {
        "state": 'Nebraska',
        "state_slug": 'nebraska',
        "postal": 'NE',
        "name": 'Pete Ricketts',
        "last": 'Ricketts',
        "slug": 'pete-ricketts',
        "qid": 'Q6106781',
        "bioguide": 'R000618',
        "enwiki_title": 'Pete Ricketts',
        "senate_class": '2',
        "party": 'Republican',
    },
    {
        "state": 'Nevada',
        "state_slug": 'nevada',
        "postal": 'NV',
        "name": 'Catherine Cortez Masto',
        "last": 'Cortez Masto',
        "slug": 'catherine-cortez-masto',
        "qid": 'Q5052604',
        "bioguide": 'C001113',
        "enwiki_title": 'Catherine Cortez Masto',
        "senate_class": '3',
        "party": 'Democrat',
    },
    {
        "state": 'Nevada',
        "state_slug": 'nevada',
        "postal": 'NV',
        "name": 'Jacky Rosen',
        "last": 'Rosen',
        "slug": 'jacky-rosen',
        "qid": 'Q27825033',
        "bioguide": 'R000608',
        "enwiki_title": 'Jacky Rosen',
        "senate_class": '1',
        "party": 'Democrat',
    },
    {
        "state": 'New Hampshire',
        "state_slug": 'new-hampshire',
        "postal": 'NH',
        "name": 'Jeanne Shaheen',
        "last": 'Shaheen',
        "slug": 'jeanne-shaheen',
        "qid": 'Q270316',
        "bioguide": 'S001181',
        "enwiki_title": 'Jeanne Shaheen',
        "senate_class": '2',
        "party": 'Democrat',
    },
    {
        "state": 'New Hampshire',
        "state_slug": 'new-hampshire',
        "postal": 'NH',
        "name": 'Margaret Wood Hassan',
        "last": 'Hassan',
        "slug": 'margaret-wood-hassan',
        "qid": 'Q24053',
        "bioguide": 'H001076',
        "enwiki_title": 'Maggie Hassan',
        "senate_class": '3',
        "party": 'Democrat',
    },
    {
        "state": 'New Jersey',
        "state_slug": 'new-jersey',
        "postal": 'NJ',
        "name": 'Andy Kim',
        "last": 'Kim',
        "slug": 'andy-kim',
        "qid": 'Q55639180',
        "bioguide": 'K000394',
        "enwiki_title": 'Andy Kim',
        "senate_class": '1',
        "party": 'Democrat',
    },
    {
        "state": 'New Jersey',
        "state_slug": 'new-jersey',
        "postal": 'NJ',
        "name": 'Cory A. Booker',
        "last": 'Booker',
        "slug": 'cory-a-booker',
        "qid": 'Q1135767',
        "bioguide": 'B001288',
        "enwiki_title": 'Cory Booker',
        "senate_class": '2',
        "party": 'Democrat',
    },
    {
        "state": 'New Mexico',
        "state_slug": 'new-mexico',
        "postal": 'NM',
        "name": 'Ben Ray Luján',
        "last": 'Luján',
        "slug": 'ben-ray-lujan',
        "qid": 'Q324256',
        "bioguide": 'L000570',
        "enwiki_title": 'Ben Ray Luján',
        "senate_class": '2',
        "party": 'Democrat',
    },
    {
        "state": 'New Mexico',
        "state_slug": 'new-mexico',
        "postal": 'NM',
        "name": 'Martin Heinrich',
        "last": 'Heinrich',
        "slug": 'martin-heinrich',
        "qid": 'Q565374',
        "bioguide": 'H001046',
        "enwiki_title": 'Martin Heinrich',
        "senate_class": '1',
        "party": 'Democrat',
    },
    {
        "state": 'New York',
        "state_slug": 'new-york',
        "postal": 'NY',
        "name": 'Charles E. Schumer',
        "last": 'Schumer',
        "slug": 'charles-e-schumer',
        "qid": 'Q380900',
        "bioguide": 'S000148',
        "enwiki_title": 'Chuck Schumer',
        "senate_class": '3',
        "party": 'Democrat',
    },
    {
        "state": 'New York',
        "state_slug": 'new-york',
        "postal": 'NY',
        "name": 'Kirsten E. Gillibrand',
        "last": 'Gillibrand',
        "slug": 'kirsten-e-gillibrand',
        "qid": 'Q22222',
        "bioguide": 'G000555',
        "enwiki_title": 'Kirsten Gillibrand',
        "senate_class": '1',
        "party": 'Democrat',
    },
    {
        "state": 'North Carolina',
        "state_slug": 'north-carolina',
        "postal": 'NC',
        "name": 'Ted Budd',
        "last": 'Budd',
        "slug": 'ted-budd',
        "qid": 'Q27733792',
        "bioguide": 'B001305',
        "enwiki_title": 'Ted Budd',
        "senate_class": '3',
        "party": 'Republican',
    },
    {
        "state": 'North Carolina',
        "state_slug": 'north-carolina',
        "postal": 'NC',
        "name": 'Thom Tillis',
        "last": 'Tillis',
        "slug": 'thom-tillis',
        "qid": 'Q7786750',
        "bioguide": 'T000476',
        "enwiki_title": 'Thom Tillis',
        "senate_class": '2',
        "party": 'Republican',
    },
    {
        "state": 'North Dakota',
        "state_slug": 'north-dakota',
        "postal": 'ND',
        "name": 'John Hoeven',
        "last": 'Hoeven',
        "slug": 'john-hoeven',
        "qid": 'Q374762',
        "bioguide": 'H001061',
        "enwiki_title": 'John Hoeven',
        "senate_class": '3',
        "party": 'Republican',
    },
    {
        "state": 'North Dakota',
        "state_slug": 'north-dakota',
        "postal": 'ND',
        "name": 'Kevin Cramer',
        "last": 'Cramer',
        "slug": 'kevin-cramer',
        "qid": 'Q3957020',
        "bioguide": 'C001096',
        "enwiki_title": 'Kevin Cramer',
        "senate_class": '1',
        "party": 'Republican',
    },
    {
        "state": 'Ohio',
        "state_slug": 'ohio',
        "postal": 'OH',
        "name": 'Bernie Moreno',
        "last": 'Moreno',
        "slug": 'bernie-moreno',
        "qid": 'Q124858476',
        "bioguide": 'M001242',
        "enwiki_title": 'Bernie Moreno',
        "senate_class": '1',
        "party": 'Republican',
    },
    {
        "state": 'Ohio',
        "state_slug": 'ohio',
        "postal": 'OH',
        "name": 'Jon Husted',
        "last": 'Husted',
        "slug": 'jon-husted',
        "qid": 'Q6270269',
        "bioguide": 'H001104',
        "enwiki_title": 'Jon Husted',
        "senate_class": '3',
        "party": 'Republican',
    },
    {
        "state": 'Oklahoma',
        "state_slug": 'oklahoma',
        "postal": 'OK',
        "name": 'Alan Armstrong',
        "last": 'Armstrong',
        "slug": 'alan-armstrong',
        "qid": 'Q138781196',
        "bioguide": 'A000383',
        "enwiki_title": 'Alan S. Armstrong',
        "senate_class": '2',
        "party": 'Republican',
    },
    {
        "state": 'Oklahoma',
        "state_slug": 'oklahoma',
        "postal": 'OK',
        "name": 'James Lankford',
        "last": 'Lankford',
        "slug": 'james-lankford',
        "qid": 'Q45940',
        "bioguide": 'L000575',
        "enwiki_title": 'James Lankford',
        "senate_class": '3',
        "party": 'Republican',
    },
    {
        "state": 'Oregon',
        "state_slug": 'oregon',
        "postal": 'OR',
        "name": 'Jeff Merkley',
        "last": 'Merkley',
        "slug": 'jeff-merkley',
        "qid": 'Q1368405',
        "bioguide": 'M001176',
        "enwiki_title": 'Jeff Merkley',
        "senate_class": '2',
        "party": 'Democrat',
    },
    {
        "state": 'Oregon',
        "state_slug": 'oregon',
        "postal": 'OR',
        "name": 'Ron Wyden',
        "last": 'Wyden',
        "slug": 'ron-wyden',
        "qid": 'Q529344',
        "bioguide": 'W000779',
        "enwiki_title": 'Ron Wyden',
        "senate_class": '3',
        "party": 'Democrat',
    },
    {
        "state": 'Pennsylvania',
        "state_slug": 'pennsylvania',
        "postal": 'PA',
        "name": 'David McCormick',
        "last": 'McCormick',
        "slug": 'david-mccormick',
        "qid": 'Q5234544',
        "bioguide": 'M001243',
        "enwiki_title": 'Dave McCormick',
        "senate_class": '1',
        "party": 'Republican',
    },
    {
        "state": 'Pennsylvania',
        "state_slug": 'pennsylvania',
        "postal": 'PA',
        "name": 'John Fetterman',
        "last": 'Fetterman',
        "slug": 'john-fetterman',
        "qid": 'Q3181500',
        "bioguide": 'F000479',
        "enwiki_title": 'John Fetterman',
        "senate_class": '3',
        "party": 'Democrat',
    },
    {
        "state": 'Rhode Island',
        "state_slug": 'rhode-island',
        "postal": 'RI',
        "name": 'Jack Reed',
        "last": 'Reed',
        "slug": 'jack-reed',
        "qid": 'Q528979',
        "bioguide": 'R000122',
        "enwiki_title": 'Jack Reed (Rhode Island politician)',
        "senate_class": '2',
        "party": 'Democrat',
    },
    {
        "state": 'Rhode Island',
        "state_slug": 'rhode-island',
        "postal": 'RI',
        "name": 'Sheldon Whitehouse',
        "last": 'Whitehouse',
        "slug": 'sheldon-whitehouse',
        "qid": 'Q652066',
        "bioguide": 'W000802',
        "enwiki_title": 'Sheldon Whitehouse',
        "senate_class": '1',
        "party": 'Democrat',
    },
    {
        "state": 'South Carolina',
        "state_slug": 'south-carolina',
        "postal": 'SC',
        "name": 'Darline Graham',
        "last": 'Graham Nordone',
        "slug": 'darline-graham',
        "qid": 'Q140537772',
        "bioguide": 'G000608',
        "enwiki_title": 'Darline Graham Nordone',
        "senate_class": '2',
        "party": 'Republican',
    },
    {
        "state": 'South Carolina',
        "state_slug": 'south-carolina',
        "postal": 'SC',
        "name": 'Tim Scott',
        "last": 'Scott',
        "slug": 'tim-scott',
        "qid": 'Q561315',
        "bioguide": 'S001184',
        "enwiki_title": 'Tim Scott',
        "senate_class": '3',
        "party": 'Republican',
    },
    {
        "state": 'South Dakota',
        "state_slug": 'south-dakota',
        "postal": 'SD',
        "name": 'John Thune',
        "last": 'Thune',
        "slug": 'john-thune',
        "qid": 'Q462981',
        "bioguide": 'T000250',
        "enwiki_title": 'John Thune',
        "senate_class": '3',
        "party": 'Republican',
    },
    {
        "state": 'South Dakota',
        "state_slug": 'south-dakota',
        "postal": 'SD',
        "name": 'Mike Rounds',
        "last": 'Rounds',
        "slug": 'mike-rounds',
        "qid": 'Q722503',
        "bioguide": 'R000605',
        "enwiki_title": 'Mike Rounds',
        "senate_class": '2',
        "party": 'Republican',
    },
    {
        "state": 'Tennessee',
        "state_slug": 'tennessee',
        "postal": 'TN',
        "name": 'Bill Hagerty',
        "last": 'Hagerty',
        "slug": 'bill-hagerty',
        "qid": 'Q27734214',
        "bioguide": 'H000601',
        "enwiki_title": 'Bill Hagerty',
        "senate_class": '2',
        "party": 'Republican',
    },
    {
        "state": 'Tennessee',
        "state_slug": 'tennessee',
        "postal": 'TN',
        "name": 'Marsha Blackburn',
        "last": 'Blackburn',
        "slug": 'marsha-blackburn',
        "qid": 'Q458971',
        "bioguide": 'B001243',
        "enwiki_title": 'Marsha Blackburn',
        "senate_class": '1',
        "party": 'Republican',
    },
    {
        "state": 'Texas',
        "state_slug": 'texas',
        "postal": 'TX',
        "name": 'John Cornyn',
        "last": 'Cornyn',
        "slug": 'john-cornyn',
        "qid": 'Q719568',
        "bioguide": 'C001056',
        "enwiki_title": 'John Cornyn',
        "senate_class": '2',
        "party": 'Republican',
    },
    {
        "state": 'Texas',
        "state_slug": 'texas',
        "postal": 'TX',
        "name": 'Ted Cruz',
        "last": 'Cruz',
        "slug": 'ted-cruz',
        "qid": 'Q2036942',
        "bioguide": 'C001098',
        "enwiki_title": 'Ted Cruz',
        "senate_class": '1',
        "party": 'Republican',
    },
    {
        "state": 'Utah',
        "state_slug": 'utah',
        "postal": 'UT',
        "name": 'John R. Curtis',
        "last": 'Curtis',
        "slug": 'john-r-curtis',
        "qid": 'Q6253810',
        "bioguide": 'C001114',
        "enwiki_title": 'John Curtis',
        "senate_class": '1',
        "party": 'Republican',
    },
    {
        "state": 'Utah',
        "state_slug": 'utah',
        "postal": 'UT',
        "name": 'Mike Lee',
        "last": 'Lee',
        "slug": 'mike-lee',
        "qid": 'Q627098',
        "bioguide": 'L000577',
        "enwiki_title": 'Mike Lee',
        "senate_class": '3',
        "party": 'Republican',
    },
    {
        "state": 'Vermont',
        "state_slug": 'vermont',
        "postal": 'VT',
        "name": 'Bernard Sanders',
        "last": 'Sanders',
        "slug": 'bernard-sanders',
        "qid": 'Q359442',
        "bioguide": 'S000033',
        "enwiki_title": 'Bernie Sanders',
        "senate_class": '1',
        "party": 'Independent',
    },
    {
        "state": 'Vermont',
        "state_slug": 'vermont',
        "postal": 'VT',
        "name": 'Peter Welch',
        "last": 'Welch',
        "slug": 'peter-welch',
        "qid": 'Q1112656',
        "bioguide": 'W000800',
        "enwiki_title": 'Peter Welch',
        "senate_class": '3',
        "party": 'Democrat',
    },
    {
        "state": 'Virginia',
        "state_slug": 'virginia',
        "postal": 'VA',
        "name": 'Mark R. Warner',
        "last": 'Warner',
        "slug": 'mark-r-warner',
        "qid": 'Q453893',
        "bioguide": 'W000805',
        "enwiki_title": 'Mark Warner',
        "senate_class": '2',
        "party": 'Democrat',
    },
    {
        "state": 'Virginia',
        "state_slug": 'virginia',
        "postal": 'VA',
        "name": 'Tim Kaine',
        "last": 'Kaine',
        "slug": 'tim-kaine',
        "qid": 'Q359888',
        "bioguide": 'K000384',
        "enwiki_title": 'Tim Kaine',
        "senate_class": '1',
        "party": 'Democrat',
    },
    {
        "state": 'Washington',
        "state_slug": 'washington',
        "postal": 'WA',
        "name": 'Maria Cantwell',
        "last": 'Cantwell',
        "slug": 'maria-cantwell',
        "qid": 'Q22250',
        "bioguide": 'C000127',
        "enwiki_title": 'Maria Cantwell',
        "senate_class": '1',
        "party": 'Democrat',
    },
    {
        "state": 'Washington',
        "state_slug": 'washington',
        "postal": 'WA',
        "name": 'Patty Murray',
        "last": 'Murray',
        "slug": 'patty-murray',
        "qid": 'Q258825',
        "bioguide": 'M001111',
        "enwiki_title": 'Patty Murray',
        "senate_class": '3',
        "party": 'Democrat',
    },
    {
        "state": 'West Virginia',
        "state_slug": 'west-virginia',
        "postal": 'WV',
        "name": 'James C. Justice',
        "last": 'Justice',
        "slug": 'james-c-justice',
        "qid": 'Q20684288',
        "bioguide": 'J000312',
        "enwiki_title": 'Jim Justice',
        "senate_class": '1',
        "party": 'Republican',
    },
    {
        "state": 'West Virginia',
        "state_slug": 'west-virginia',
        "postal": 'WV',
        "name": 'Shelley Moore Capito',
        "last": 'Capito',
        "slug": 'shelley-moore-capito',
        "qid": 'Q459618',
        "bioguide": 'C001047',
        "enwiki_title": 'Shelley Moore Capito',
        "senate_class": '2',
        "party": 'Republican',
    },
    {
        "state": 'Wisconsin',
        "state_slug": 'wisconsin',
        "postal": 'WI',
        "name": 'Ron Johnson',
        "last": 'Johnson',
        "slug": 'ron-johnson',
        "qid": 'Q970272',
        "bioguide": 'J000293',
        "enwiki_title": 'Ron Johnson',
        "senate_class": '3',
        "party": 'Republican',
    },
    {
        "state": 'Wisconsin',
        "state_slug": 'wisconsin',
        "postal": 'WI',
        "name": 'Tammy Baldwin',
        "last": 'Baldwin',
        "slug": 'tammy-baldwin',
        "qid": 'Q40628',
        "bioguide": 'B001230',
        "enwiki_title": 'Tammy Baldwin',
        "senate_class": '1',
        "party": 'Democrat',
    },
    {
        "state": 'Wyoming',
        "state_slug": 'wyoming',
        "postal": 'WY',
        "name": 'Cynthia M. Lummis',
        "last": 'Lummis',
        "slug": 'cynthia-m-lummis',
        "qid": 'Q456064',
        "bioguide": 'L000571',
        "enwiki_title": 'Cynthia Lummis',
        "senate_class": '2',
        "party": 'Republican',
    },
    {
        "state": 'Wyoming',
        "state_slug": 'wyoming',
        "postal": 'WY',
        "name": 'John Barrasso',
        "last": 'Barrasso',
        "slug": 'john-barrasso',
        "qid": 'Q720521',
        "bioguide": 'B001261',
        "enwiki_title": 'John Barrasso',
        "senate_class": '1',
        "party": 'Republican',
    },
)

SITTING_QIDS: tuple[str, ...] = tuple(row["qid"] for row in SITTING_SENATORS)
SITTING_SLUGS: tuple[str, ...] = tuple(row["slug"] for row in SITTING_SENATORS)
SITTING_BIOGUIDES: tuple[str, ...] = tuple(row["bioguide"] for row in SITTING_SENATORS)
SITTING_STATES: tuple[str, ...] = tuple(sorted({row["state"] for row in SITTING_SENATORS}))

