"""Curated Declaration-signer catalog.

Primary dates: NARA Signers Factsheet. Wikipedia infobox + Bioguide are
corroboration. Wikidata P569 precision=11 is QA only — never a date source.

Do not invent day-of-year values. Year-only NARA rows stay year-only even
when Wikidata or Wikipedia later claims a day.
"""

from __future__ import annotations

from typing import Literal

NARA_FACTSHEET_URL = "https://www.archives.gov/founding-docs/signers-factsheet"
NARA_FACTSHEET_PDF = (
    "https://www.archives.gov/files/founding-docs/declaration-signers-gallery-facts.pdf"
)
BIOGUIDE_URL = "https://bioguide.congress.gov/search/bio/{id}"

SignerStatus = Literal["verified", "year_only", "contested"]
CalendarNote = Literal["new_style", "nara_day"]

COLONY_NAMES: dict[str, str] = {
    "CT": "Connecticut",
    "DE": "Delaware",
    "GA": "Georgia",
    "MD": "Maryland",
    "MA": "Massachusetts",
    "NH": "New Hampshire",
    "NJ": "New Jersey",
    "NY": "New York",
    "NC": "North Carolina",
    "PA": "Pennsylvania",
    "RI": "Rhode Island",
    "SC": "South Carolina",
    "VA": "Virginia",
}

YEAR_ONLY_NOTE = (
    "NARA records only a year (circa). The day of birth is unknown. "
    "No birth card is computed and no signer page is published."
)

HANCOCK_HOLD = (
    "Held: NARA lists 1/12/1737 (Old Style); Wikipedia lists January 23, 1737 "
    "(New Style). The OS/NS pair is contested for this set."
)
HARRISON_HOLD = (
    "Held: NARA lists 4/7/1726; Wikipedia lists April 5, 1726. "
    "The day is contested."
)
HEWES_HOLD = (
    "Held: NARA and the Wikipedia infobox list July 9, 1730, but a January 23, "
    "1730 variant remains in circulation. The day is contested."
)


def _entry(
    *,
    name: str,
    slug: str,
    colony_code: str,
    wikipedia_title: str,
    qid: str,
    bioguide_id: str,
    nara_birth_raw: str,
    nara_death: str | None,
    status: SignerStatus,
    public_birth_date: str | None,
    wikipedia_birth: str | None,
    calendar_note: CalendarNote | None,
    footnote: str | None,
    hold_reason: str | None = None,
) -> dict:
    return {
        "name": name,
        "slug": slug,
        "colony_code": colony_code,
        "colony": COLONY_NAMES[colony_code],
        "wikipedia_title": wikipedia_title,
        "qid": qid,
        "bioguide_id": bioguide_id,
        "nara_birth_raw": nara_birth_raw,
        "nara_death": nara_death,
        "status": status,
        "public_birth_date": public_birth_date,
        "wikipedia_birth": wikipedia_birth,
        "calendar_note": calendar_note,
        "footnote": footnote,
        "hold_reason": hold_reason,
    }


# 56 signers in NARA last-name order. public_birth_date is set only when
# status == verified. Year-only and contested rows keep that field None.
SIGNERS: tuple[dict, ...] = (
    _entry(
        name="John Adams",
        slug="john-adams",
        colony_code="MA",
        wikipedia_title="John Adams",
        qid="Q11806",
        bioguide_id="A000039",
        nara_birth_raw="10/30/1735",
        nara_death="1826-07-04",
        status="verified",
        public_birth_date="1735-10-30",
        wikipedia_birth="1735-10-30",
        calendar_note="new_style",
        footnote="NARA and Wikipedia both list October 30, 1735 (New Style; Old Style October 19).",
    ),
    _entry(
        name="Samuel Adams",
        slug="samuel-adams",
        colony_code="MA",
        wikipedia_title="Samuel Adams",
        qid="Q212963",
        bioguide_id="A000045",
        nara_birth_raw="9/27/1722",
        nara_death="1803-10-02",
        status="verified",
        public_birth_date="1722-09-27",
        wikipedia_birth="1722-09-27",
        calendar_note="new_style",
        footnote="NARA and Wikipedia both list September 27, 1722 (New Style; Old Style September 16).",
    ),
    _entry(
        name="Josiah Bartlett",
        slug="josiah-bartlett",
        colony_code="NH",
        wikipedia_title="Josiah Bartlett",
        qid="Q710057",
        bioguide_id="B000206",
        nara_birth_raw="11/21/1729",
        nara_death="1795-05-19",
        status="verified",
        public_birth_date="1729-12-02",
        wikipedia_birth="1729-12-02",
        calendar_note="new_style",
        footnote="NARA lists 11/21/1729 (Old Style). Wikipedia New Style is December 2, 1729.",
    ),
    _entry(
        name="Carter Braxton",
        slug="carter-braxton",
        colony_code="VA",
        wikipedia_title="Carter Braxton",
        qid="Q647979",
        bioguide_id="B000773",
        nara_birth_raw="9/10/1736",
        nara_death="1797-10-10",
        status="verified",
        public_birth_date="1736-09-10",
        wikipedia_birth="1736-09-10",
        calendar_note="nara_day",
        footnote=None,
    ),
    _entry(
        name="Charles Carroll of Carrollton",
        slug="charles-carroll-of-carrollton",
        colony_code="MD",
        wikipedia_title="Charles Carroll of Carrollton",
        qid="Q466009",
        bioguide_id="C000185",
        nara_birth_raw="9/19/1737",
        nara_death="1832-11-14",
        status="verified",
        public_birth_date="1737-09-19",
        wikipedia_birth="1737-09-19",
        calendar_note="nara_day",
        footnote=None,
    ),
    _entry(
        name="Samuel Chase",
        slug="samuel-chase",
        colony_code="MD",
        wikipedia_title="Samuel Chase",
        qid="Q285521",
        bioguide_id="C000334",
        nara_birth_raw="4/17/1741",
        nara_death="1811-06-19",
        status="verified",
        public_birth_date="1741-04-17",
        wikipedia_birth="1741-04-17",
        calendar_note="nara_day",
        footnote=None,
    ),
    _entry(
        name="Abraham Clark",
        slug="abraham-clark",
        colony_code="NJ",
        wikipedia_title="Abraham Clark",
        qid="Q329870",
        bioguide_id="C000420",
        nara_birth_raw="2/15/1726",
        nara_death="1794-09-15",
        status="verified",
        public_birth_date="1726-02-15",
        wikipedia_birth="1726-02-15",
        calendar_note="nara_day",
        footnote=None,
    ),
    _entry(
        name="George Clymer",
        slug="george-clymer",
        colony_code="PA",
        wikipedia_title="George Clymer",
        qid="Q708913",
        bioguide_id="C000538",
        nara_birth_raw="3/16/1739",
        nara_death="1813-01-24",
        status="verified",
        public_birth_date="1739-03-16",
        wikipedia_birth="1739-03-16",
        calendar_note="nara_day",
        footnote=None,
    ),
    _entry(
        name="William Ellery",
        slug="william-ellery",
        colony_code="RI",
        wikipedia_title="William Ellery",
        qid="Q567964",
        bioguide_id="E000112",
        nara_birth_raw="12/22/1727",
        nara_death="1820-02-15",
        status="verified",
        public_birth_date="1727-12-22",
        wikipedia_birth="1727-12-22",
        calendar_note="nara_day",
        footnote=None,
    ),
    _entry(
        name="William Floyd",
        slug="william-floyd",
        colony_code="NY",
        wikipedia_title="William Floyd",
        qid="Q1381060",
        bioguide_id="F000221",
        nara_birth_raw="12/17/1734",
        nara_death="1821-08-04",
        status="verified",
        public_birth_date="1734-12-17",
        wikipedia_birth="1734-12-17",
        calendar_note="nara_day",
        footnote=None,
    ),
    _entry(
        name="Benjamin Franklin",
        slug="benjamin-franklin",
        colony_code="PA",
        wikipedia_title="Benjamin Franklin",
        qid="Q34969",
        bioguide_id="F000347",
        nara_birth_raw="1/17/1706",
        nara_death="1790-04-17",
        status="verified",
        public_birth_date="1706-01-17",
        wikipedia_birth="1706-01-17",
        calendar_note="new_style",
        footnote="NARA and Wikipedia both list January 17, 1706 (New Style; Old Style January 6, 1705/06).",
    ),
    _entry(
        name="Elbridge Gerry",
        slug="elbridge-gerry",
        colony_code="MA",
        wikipedia_title="Elbridge Gerry",
        qid="Q219797",
        bioguide_id="G000139",
        nara_birth_raw="7/17/1744",
        nara_death="1814-11-23",
        status="verified",
        public_birth_date="1744-07-17",
        wikipedia_birth="1744-07-17",
        calendar_note="nara_day",
        footnote=None,
    ),
    _entry(
        name="Button Gwinnett",
        slug="button-gwinnett",
        colony_code="GA",
        wikipedia_title="Button Gwinnett",
        qid="Q887136",
        bioguide_id="G000536",
        nara_birth_raw="c. 1735",
        nara_death="1777-05-15",
        status="year_only",
        public_birth_date=None,
        wikipedia_birth=None,
        calendar_note=None,
        footnote=YEAR_ONLY_NOTE,
    ),
    _entry(
        name="Lyman Hall",
        slug="lyman-hall",
        colony_code="GA",
        wikipedia_title="Lyman Hall",
        qid="Q590856",
        bioguide_id="H000061",
        nara_birth_raw="4/12/1724",
        nara_death="1790-10-19",
        status="verified",
        public_birth_date="1724-04-12",
        wikipedia_birth="1724-04-12",
        calendar_note="nara_day",
        footnote=None,
    ),
    _entry(
        name="John Hancock",
        slug="john-hancock",
        colony_code="MA",
        wikipedia_title="John Hancock",
        qid="Q272774",
        bioguide_id="H000177",
        nara_birth_raw="1/12/1737",
        nara_death="1793-10-08",
        status="contested",
        public_birth_date=None,
        wikipedia_birth="1737-01-23",
        calendar_note=None,
        footnote=HANCOCK_HOLD,
        hold_reason="hancock_os_ns",
    ),
    _entry(
        name="Benjamin Harrison V",
        slug="benjamin-harrison-v",
        colony_code="VA",
        wikipedia_title="Benjamin Harrison V",
        qid="Q387664",
        bioguide_id="H000263",
        nara_birth_raw="4/7/1726",
        nara_death="1791-04-24",
        status="contested",
        public_birth_date=None,
        wikipedia_birth="1726-04-05",
        calendar_note=None,
        footnote=HARRISON_HOLD,
        hold_reason="harrison_v",
    ),
    _entry(
        name="John Hart",
        slug="john-hart",
        colony_code="NJ",
        wikipedia_title="John Hart (New Jersey politician)",
        qid="Q1367952",
        bioguide_id="H000287",
        nara_birth_raw="c. 1711",
        nara_death="1779-05-11",
        status="year_only",
        public_birth_date=None,
        wikipedia_birth=None,
        calendar_note=None,
        footnote=YEAR_ONLY_NOTE,
    ),
    _entry(
        name="Joseph Hewes",
        slug="joseph-hewes",
        colony_code="NC",
        wikipedia_title="Joseph Hewes",
        qid="Q1666382",
        bioguide_id="H000547",
        nara_birth_raw="7/9/1730",
        nara_death="1779-10-10",
        status="contested",
        public_birth_date=None,
        wikipedia_birth="1730-07-09",
        calendar_note=None,
        footnote=HEWES_HOLD,
        hold_reason="hewes",
    ),
    _entry(
        name="Thomas Heyward Jr.",
        slug="thomas-heyward-jr",
        colony_code="SC",
        wikipedia_title="Thomas Heyward Jr.",
        qid="Q1399545",
        bioguide_id="H000552",
        nara_birth_raw="7/28/1746",
        nara_death="1809-03-06",
        status="verified",
        public_birth_date="1746-07-28",
        wikipedia_birth="1746-07-28",
        calendar_note="nara_day",
        footnote=None,
    ),
    _entry(
        name="William Hooper",
        slug="william-hooper",
        colony_code="NC",
        wikipedia_title="William Hooper",
        qid="Q1345669",
        bioguide_id="H000763",
        nara_birth_raw="6/17/1742",
        nara_death="1790-10-14",
        status="verified",
        public_birth_date="1742-06-28",
        wikipedia_birth="1742-06-17",
        calendar_note="new_style",
        footnote="Wikipedia marks June 17, 1742 as Old Style. New Style is June 28, 1742.",
    ),
    _entry(
        name="Stephen Hopkins",
        slug="stephen-hopkins",
        colony_code="RI",
        wikipedia_title="Stephen Hopkins (politician)",
        qid="Q1399643",
        bioguide_id="H000776",
        nara_birth_raw="3/7/1707",
        nara_death="1785-04-13",
        status="verified",
        public_birth_date="1707-03-07",
        wikipedia_birth="1707-03-07",
        calendar_note="nara_day",
        footnote=None,
    ),
    _entry(
        name="Francis Hopkinson",
        slug="francis-hopkinson",
        colony_code="NJ",
        wikipedia_title="Francis Hopkinson",
        qid="Q1397375",
        bioguide_id="H000788",
        nara_birth_raw="10/2/1737",
        nara_death="1791-05-09",
        status="verified",
        public_birth_date="1737-10-02",
        wikipedia_birth="1737-10-02",
        calendar_note="new_style",
        footnote="NARA and Wikipedia list October 2, 1737 (New Style; Old Style September 21).",
    ),
    _entry(
        name="Samuel Huntington",
        slug="samuel-huntington",
        colony_code="CT",
        wikipedia_title="Samuel Huntington (Connecticut politician)",
        qid="Q887130",
        bioguide_id="H000999",
        nara_birth_raw="7/3/1731",
        nara_death="1796-01-05",
        status="verified",
        public_birth_date="1731-07-16",
        wikipedia_birth="1731-07-16",
        calendar_note="new_style",
        footnote=(
            "NARA lists 7/3/1731 (smudged town-record Old Style). Wikipedia and his "
            "coffin plate use New Style July 16, 1731."
        ),
    ),
    _entry(
        name="Thomas Jefferson",
        slug="thomas-jefferson",
        colony_code="VA",
        wikipedia_title="Thomas Jefferson",
        qid="Q11812",
        bioguide_id="J000069",
        nara_birth_raw="4/13/1743",
        nara_death="1826-07-04",
        status="verified",
        public_birth_date="1743-04-13",
        wikipedia_birth="1743-04-13",
        calendar_note="nara_day",
        footnote=None,
    ),
    _entry(
        name="Francis Lightfoot Lee",
        slug="francis-lightfoot-lee",
        colony_code="VA",
        wikipedia_title="Francis Lightfoot Lee",
        qid="Q709825",
        bioguide_id="L000190",
        nara_birth_raw="10/14/1734",
        nara_death="1797-01-11",
        status="verified",
        public_birth_date="1734-10-14",
        wikipedia_birth="1734-10-14",
        calendar_note="nara_day",
        footnote=None,
    ),
    _entry(
        name="Richard Henry Lee",
        slug="richard-henry-lee",
        colony_code="VA",
        wikipedia_title="Richard Henry Lee",
        qid="Q725907",
        bioguide_id="L000201",
        nara_birth_raw="1/20/1732",
        nara_death="1794-06-19",
        status="verified",
        public_birth_date="1732-01-20",
        wikipedia_birth="1732-01-20",
        calendar_note="nara_day",
        footnote=None,
    ),
    _entry(
        name="Francis Lewis",
        slug="francis-lewis",
        colony_code="NY",
        wikipedia_title="Francis Lewis",
        qid="Q223235",
        bioguide_id="L000277",
        nara_birth_raw="3/21/1713",
        nara_death="1802-12-30",
        status="verified",
        public_birth_date="1713-03-21",
        wikipedia_birth="1713-03-21",
        calendar_note="nara_day",
        footnote=None,
    ),
    _entry(
        name="Philip Livingston",
        slug="philip-livingston",
        colony_code="NY",
        wikipedia_title="Philip Livingston",
        qid="Q714967",
        bioguide_id="L000372",
        nara_birth_raw="1/15/1716",
        nara_death="1778-06-12",
        status="verified",
        public_birth_date="1716-01-15",
        wikipedia_birth="1716-01-15",
        calendar_note="nara_day",
        footnote=None,
    ),
    _entry(
        name="Thomas Lynch Jr.",
        slug="thomas-lynch-jr",
        colony_code="SC",
        wikipedia_title="Thomas Lynch Jr.",
        qid="Q537583",
        bioguide_id="L000533",
        nara_birth_raw="8/5/1749",
        nara_death=None,
        status="verified",
        public_birth_date="1749-08-05",
        wikipedia_birth="1749-08-05",
        calendar_note="nara_day",
        footnote="NARA records death as circa 1779 (lost at sea). No death day is published here.",
    ),
    _entry(
        name="Thomas McKean",
        slug="thomas-mckean",
        colony_code="DE",
        wikipedia_title="Thomas McKean",
        qid="Q880686",
        bioguide_id="M000492",
        nara_birth_raw="3/19/1735",
        nara_death="1817-06-24",
        status="verified",
        public_birth_date="1735-03-19",
        wikipedia_birth="1734-03-19",
        calendar_note="new_style",
        footnote=(
            "NARA lists March 19, 1735 (New Style year). Wikipedia lists March 19, 1734 "
            "(1734/35 double dating). Same month and day; year follows NARA New Style."
        ),
    ),
    _entry(
        name="Arthur Middleton",
        slug="arthur-middleton",
        colony_code="SC",
        wikipedia_title="Arthur Middleton",
        qid="Q657569",
        bioguide_id="M000701",
        nara_birth_raw="6/26/1742",
        nara_death="1787-01-01",
        status="verified",
        public_birth_date="1742-06-26",
        wikipedia_birth="1742-06-26",
        calendar_note="nara_day",
        footnote=None,
    ),
    _entry(
        name="Lewis Morris",
        slug="lewis-morris",
        colony_code="NY",
        wikipedia_title="Lewis Morris",
        qid="Q328181",
        bioguide_id="M000976",
        nara_birth_raw="4/8/1726",
        nara_death="1798-01-22",
        status="verified",
        public_birth_date="1726-04-08",
        wikipedia_birth="1726-04-08",
        calendar_note="nara_day",
        footnote=None,
    ),
    _entry(
        name="Robert Morris",
        slug="robert-morris",
        colony_code="PA",
        wikipedia_title="Robert Morris (financier)",
        qid="Q464876",
        bioguide_id="M000985",
        nara_birth_raw="1/31/1734",
        nara_death="1806-05-08",
        status="verified",
        public_birth_date="1734-01-31",
        wikipedia_birth="1734-01-20",
        calendar_note="new_style",
        footnote="NARA lists January 31, 1734 (New Style). Wikipedia lists January 20 (Old Style).",
    ),
    _entry(
        name="John Morton",
        slug="john-morton",
        colony_code="PA",
        wikipedia_title="John Morton (American politician)",
        qid="Q1230175",
        bioguide_id="M001017",
        nara_birth_raw="c. 1724",
        nara_death=None,
        status="year_only",
        public_birth_date=None,
        wikipedia_birth=None,
        calendar_note=None,
        footnote=YEAR_ONLY_NOTE,
    ),
    _entry(
        name="Thomas Nelson Jr.",
        slug="thomas-nelson-jr",
        colony_code="VA",
        wikipedia_title="Thomas Nelson Jr.",
        qid="Q880222",
        bioguide_id="N000040",
        nara_birth_raw="12/26/1738",
        nara_death="1789-01-04",
        status="verified",
        public_birth_date="1738-12-26",
        wikipedia_birth="1738-12-26",
        calendar_note="nara_day",
        footnote=None,
    ),
    _entry(
        name="William Paca",
        slug="william-paca",
        colony_code="MD",
        wikipedia_title="William Paca",
        qid="Q766814",
        bioguide_id="P000001",
        nara_birth_raw="10/31/1740",
        nara_death="1799-10-13",
        status="verified",
        public_birth_date="1740-10-31",
        wikipedia_birth="1740-10-31",
        calendar_note="nara_day",
        footnote=None,
    ),
    _entry(
        name="Robert Treat Paine",
        slug="robert-treat-paine",
        colony_code="MA",
        wikipedia_title="Robert Treat Paine",
        qid="Q743472",
        bioguide_id="P000031",
        nara_birth_raw="3/11/1731",
        nara_death="1814-05-12",
        status="verified",
        public_birth_date="1731-03-11",
        wikipedia_birth="1731-03-11",
        calendar_note="nara_day",
        footnote=None,
    ),
    _entry(
        name="John Penn",
        slug="john-penn",
        colony_code="NC",
        wikipedia_title="John Penn (North Carolina politician)",
        qid="Q530037",
        bioguide_id="P000241",
        nara_birth_raw="5/6/1740",
        nara_death="1788-09-14",
        status="verified",
        public_birth_date="1740-05-06",
        wikipedia_birth="1741-05-17",
        calendar_note="nara_day",
        footnote="NARA lists 5/6/1740. Wikipedia lists May 17, 1741. This page keeps the NARA day.",
    ),
    _entry(
        name="George Read",
        slug="george-read",
        colony_code="DE",
        wikipedia_title="George Read (American politician, born 1733)",
        qid="Q471303",
        bioguide_id="R000092",
        nara_birth_raw="9/18/1733",
        nara_death="1798-09-21",
        status="verified",
        public_birth_date="1733-09-18",
        wikipedia_birth="1733-09-18",
        calendar_note="nara_day",
        footnote=None,
    ),
    _entry(
        name="Caesar Rodney",
        slug="caesar-rodney",
        colony_code="DE",
        wikipedia_title="Caesar Rodney",
        qid="Q887100",
        bioguide_id="R000377",
        nara_birth_raw="10/7/1728",
        nara_death="1784-06-29",
        status="verified",
        public_birth_date="1728-10-07",
        wikipedia_birth="1728-10-07",
        calendar_note="nara_day",
        footnote=None,
    ),
    _entry(
        name="George Ross",
        slug="george-ross",
        colony_code="PA",
        wikipedia_title="George Ross (American politician)",
        qid="Q655575",
        bioguide_id="R000438",
        nara_birth_raw="5/10/1730",
        nara_death="1779-07-14",
        status="verified",
        public_birth_date="1730-05-10",
        wikipedia_birth="1730-05-10",
        calendar_note="nara_day",
        footnote=None,
    ),
    _entry(
        name="Benjamin Rush",
        slug="benjamin-rush",
        colony_code="PA",
        wikipedia_title="Benjamin Rush",
        qid="Q656478",
        bioguide_id="R000507",
        nara_birth_raw="1/4/1746",
        nara_death="1813-04-19",
        status="verified",
        public_birth_date="1746-01-04",
        wikipedia_birth="1746-01-04",
        calendar_note="new_style",
        footnote="NARA and Wikipedia list January 4, 1746 (New Style; Old Style December 24, 1745).",
    ),
    _entry(
        name="Edward Rutledge",
        slug="edward-rutledge",
        colony_code="SC",
        wikipedia_title="Edward Rutledge",
        qid="Q878666",
        bioguide_id="R000549",
        nara_birth_raw="11/23/1749",
        nara_death="1800-01-23",
        status="verified",
        public_birth_date="1749-11-23",
        wikipedia_birth="1749-11-23",
        calendar_note="nara_day",
        footnote=None,
    ),
    _entry(
        name="Roger Sherman",
        slug="roger-sherman",
        colony_code="CT",
        wikipedia_title="Roger Sherman",
        qid="Q354721",
        bioguide_id="S000346",
        nara_birth_raw="4/19/1721",
        nara_death="1793-07-23",
        status="verified",
        public_birth_date="1721-04-19",
        wikipedia_birth="1721-04-19",
        calendar_note="nara_day",
        footnote=None,
    ),
    _entry(
        name="James Smith",
        slug="james-smith",
        colony_code="PA",
        wikipedia_title="James Smith (Pennsylvania politician)",
        qid="Q721599",
        bioguide_id="S000554",
        nara_birth_raw="c. 1719",
        nara_death="1806-07-11",
        status="year_only",
        public_birth_date=None,
        wikipedia_birth=None,
        calendar_note=None,
        footnote=YEAR_ONLY_NOTE,
    ),
    _entry(
        name="Richard Stockton",
        slug="richard-stockton",
        colony_code="NJ",
        wikipedia_title="Richard Stockton (Continental Congressman)",
        qid="Q550569",
        bioguide_id="S000919",
        nara_birth_raw="10/1/1730",
        nara_death="1781-02-28",
        status="verified",
        public_birth_date="1730-10-01",
        wikipedia_birth="1730-10-01",
        calendar_note="nara_day",
        footnote=None,
    ),
    _entry(
        name="Thomas Stone",
        slug="thomas-stone",
        colony_code="MD",
        wikipedia_title="Thomas Stone",
        qid="Q721842",
        bioguide_id="S000961",
        nara_birth_raw="c. 1743",
        nara_death="1787-10-05",
        status="year_only",
        public_birth_date=None,
        wikipedia_birth=None,
        calendar_note=None,
        footnote=YEAR_ONLY_NOTE,
    ),
    _entry(
        name="George Taylor",
        slug="george-taylor",
        colony_code="PA",
        wikipedia_title="George Taylor (Pennsylvania politician)",
        qid="Q1369216",
        bioguide_id="T000082",
        nara_birth_raw="c. 1716",
        nara_death="1781-02-23",
        status="year_only",
        public_birth_date=None,
        wikipedia_birth=None,
        calendar_note=None,
        footnote=YEAR_ONLY_NOTE,
    ),
    _entry(
        name="Matthew Thornton",
        slug="matthew-thornton",
        colony_code="NH",
        wikipedia_title="Matthew Thornton",
        qid="Q1368351",
        bioguide_id="T000241",
        nara_birth_raw="c. 1714",
        nara_death="1803-06-24",
        status="year_only",
        public_birth_date=None,
        wikipedia_birth=None,
        calendar_note=None,
        footnote=YEAR_ONLY_NOTE,
    ),
    _entry(
        name="George Walton",
        slug="george-walton",
        colony_code="GA",
        wikipedia_title="George Walton",
        qid="Q878512",
        bioguide_id="W000113",
        nara_birth_raw="c. 1741",
        nara_death="1804-02-02",
        status="year_only",
        public_birth_date=None,
        wikipedia_birth=None,
        calendar_note=None,
        footnote=YEAR_ONLY_NOTE,
    ),
    _entry(
        name="William Whipple",
        slug="william-whipple",
        colony_code="NH",
        wikipedia_title="William Whipple",
        qid="Q1969780",
        bioguide_id="W000355",
        nara_birth_raw="1/14/1730",
        nara_death="1785-11-28",
        status="verified",
        public_birth_date="1730-01-14",
        wikipedia_birth="1730-01-14",
        calendar_note="nara_day",
        footnote=None,
    ),
    _entry(
        name="William Williams",
        slug="william-williams",
        colony_code="CT",
        wikipedia_title="William Williams (Connecticut politician)",
        qid="Q718341",
        bioguide_id="W000546",
        nara_birth_raw="4/18/1731",
        nara_death="1811-08-02",
        status="verified",
        public_birth_date="1731-04-18",
        wikipedia_birth="1731-04-09",
        calendar_note="nara_day",
        footnote="NARA lists 4/18/1731. Wikipedia lists April 9, 1731. This page keeps the NARA day.",
    ),
    _entry(
        name="James Wilson",
        slug="james-wilson",
        colony_code="PA",
        wikipedia_title="James Wilson (Founding Father)",
        qid="Q365181",
        bioguide_id="W000577",
        nara_birth_raw="9/14/1742",
        nara_death="1798-08-21",
        status="verified",
        public_birth_date="1742-09-14",
        wikipedia_birth="1742-09-14",
        calendar_note="nara_day",
        footnote=None,
    ),
    _entry(
        name="John Witherspoon",
        slug="john-witherspoon",
        colony_code="NJ",
        wikipedia_title="John Witherspoon",
        qid="Q1246390",
        bioguide_id="W000655",
        nara_birth_raw="2/5/1723",
        nara_death="1794-11-15",
        status="verified",
        public_birth_date="1723-02-05",
        wikipedia_birth="1723-02-05",
        calendar_note="nara_day",
        footnote=None,
    ),
    _entry(
        name="Oliver Wolcott",
        slug="oliver-wolcott",
        colony_code="CT",
        wikipedia_title="Oliver Wolcott",
        qid="Q731813",
        bioguide_id="W000669",
        nara_birth_raw="11/20/1726",
        nara_death="1797-12-01",
        status="verified",
        public_birth_date="1726-11-20",
        wikipedia_birth="1726-11-20",
        calendar_note="nara_day",
        footnote=None,
    ),
    _entry(
        name="George Wythe",
        slug="george-wythe",
        colony_code="VA",
        wikipedia_title="George Wythe",
        qid="Q1397321",
        bioguide_id="W000787",
        nara_birth_raw="c. 1726",
        nara_death="1806-06-08",
        status="year_only",
        public_birth_date=None,
        wikipedia_birth=None,
        calendar_note=None,
        footnote=YEAR_ONLY_NOTE,
    ),
)


def signers_by_status(status: SignerStatus) -> list[dict]:
    return [row for row in SIGNERS if row["status"] == status]


def verified_signers() -> list[dict]:
    return signers_by_status("verified")


def year_only_signers() -> list[dict]:
    return signers_by_status("year_only")


def contested_signers() -> list[dict]:
    return signers_by_status("contested")


def bioguide_url(bioguide_id: str) -> str:
    return BIOGUIDE_URL.format(id=bioguide_id)
