import type { Metadata } from "next";
import Link from "next/link";

import { SeoShell } from "@/components/seo/SeoShell";
import { Kicker, LinkButton, MobileActionBar, PricingCard } from "@/components/ui";
import {
  FAIR_USE_COPY,
  FREE_PREVIEW_BLURB,
  MICROTRUST_LINE,
  READER_PHONE_DISPLAY,
  READER_PHONE_TEL,
  SEASON_PASS_CLARIFIER,
} from "@/lib/offers";
import { READING_OFFERS } from "@/lib/products";
import { SITE_NAME, SITE_URL } from "@/lib/site";

export const dynamic = "force-static";

export const metadata: Metadata = {
  title: "Cardology Readings: $19 Question, $39 Complete Reading, $199 Season Pass",
  description:
    "Choose a voice reading with the AI Cardology reader: a $19 Quick Question, the $39 Complete Reading, or a $199 90-Day Season Pass. Hear your first card free before you buy.",
  alternates: { canonical: "/readings" },
  openGraph: {
    siteName: SITE_NAME,
    title: "Cardology Voice Readings by Phone",
    description:
      "A $19 Quick Question, the $39 Complete Reading, or a $199 90-Day Season Pass — all by phone with the AI Cardology reader.",
    url: "/readings",
    type: "website",
    images: [{ url: "/og/default.png", width: 1200, height: 630, alt: "Card Blueprints" }],
  },
};

const visibleFaqs = [
  {
    q: "Is the reader AI?",
    a: "Yes. Every reading on this line is delivered by an AI voice reader, not a human. The birth-card calculation underneath it is deterministic — the same birthday always produces the same card — while the spoken conversation is generated by AI and can make mistakes.",
  },
  {
    q: "What information do I need?",
    a: "A birth date — yours, or the person the question is about. For relationship questions, bring both birthdays. The reader asks for what it needs during the call; no account or forms are required.",
  },
  {
    q: "What counts as a paid session?",
    a: "A completed paid call. The Quick Question and Complete Reading each include one paid session; a call that fails to connect or ends immediately is not meant to consume your session. Call from the phone number you used at checkout so the reader recognizes your access.",
  },
  {
    q: "What does unlimited mean on the Season Pass?",
    a: `Unlimited personal return calls for 90 days, subject to fair use: ${FAIR_USE_COPY.charAt(0).toLowerCase()}${FAIR_USE_COPY.slice(1)}`,
  },
  {
    q: "Does the 90-Day Season Pass automatically renew?",
    a: "No. The Season Pass is a single one-time payment. When the 90 days end, access simply ends — there is no subscription and nothing to cancel.",
  },
  {
    q: "What is the refund policy?",
    a: "Voice access can be refunded in full before your first paid session is used. After paid usage begins, refunds are limited and reviewed fairly — if the line did not work or access was not recognized, contact us and we will make it right. See the refund policy for details.",
  },
];

export default function ReadingsPage() {
  const jsonLd = [
    {
      "@context": "https://schema.org",
      "@type": "CollectionPage",
      name: "Cardology Voice Readings",
      description: metadata.description,
      url: `${SITE_URL}/readings`,
      publisher: { "@id": `${SITE_URL}/#organization` },
      mainEntity: {
        "@type": "ItemList",
        itemListElement: READING_OFFERS.map((offer, index) => ({
          "@type": "ListItem",
          position: index + 1,
          name: offer.name,
          url: `${SITE_URL}/readings#${offer.slug}`,
        })),
      },
    },
    {
      "@context": "https://schema.org",
      "@type": "FAQPage",
      mainEntity: visibleFaqs.map((faq) => ({
        "@type": "Question",
        name: faq.q,
        acceptedAnswer: { "@type": "Answer", text: faq.a },
      })),
    },
  ];

  return (
    <SeoShell crumb={[{ label: "Home", href: "/" }, { label: "Readings", href: "/readings" }]}>
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }} />

      {/* 1 — Voice-first hero */}
      <header className="pb-10">
        <Kicker className="mb-4">Voice readings &middot; by phone</Kicker>
        <h1 className="type-display max-w-[44rem] text-brand-ink">
          Choose how deep you want to go.
        </h1>
        <p className="type-body-lg mt-6 max-w-[38em] text-brand-ink-soft">
          Ask one focused question, hear your complete pattern, or keep the
          reader available for the next 90 days.
        </p>
      </header>

      {/* 2 — Free-preview callout */}
      <section className="border-y border-brand-line py-7">
        <div className="grid gap-5 sm:grid-cols-[1fr_auto] sm:items-center">
          <div>
            <h2 className="type-h3 text-brand-ink">Hear your first card before you buy.</h2>
            <p className="mt-2 max-w-[38em] text-sm leading-relaxed text-brand-ink-soft">
              {FREE_PREVIEW_BLURB}
            </p>
          </div>
          <LinkButton href={READER_PHONE_TEL} variant="primary" size="large">
            Call Free: {READER_PHONE_DISPLAY}
          </LinkButton>
        </div>
      </section>

      {/* 3 — Three pricing cards */}
      <section id="pricing" className="mt-12">
        <div className="grid gap-5 lg:grid-cols-3">
          {READING_OFFERS.map((offer) => (
            <PricingCard
              key={offer.slug}
              offer={offer}
              emphasized={offer.slug === "complete-reading"}
              goldAccent={offer.slug === "season-pass-90"}
            />
          ))}
        </div>
        <div className="mt-6 space-y-1 text-center text-xs leading-relaxed text-brand-ink-soft">
          <p>{MICROTRUST_LINE}</p>
          <p>{SEASON_PASS_CLARIFIER}</p>
        </div>
      </section>

      {/* 4 — How it works */}
      <section className="mt-16">
        <Kicker>How it works</Kicker>
        <div className="mt-6 grid gap-8 lg:grid-cols-3">
          {[
            {
              label: "01",
              title: "Choose your reading.",
              detail: "Pick one focused question, a complete reading, or ongoing seasonal access.",
            },
            {
              label: "02",
              title: "Check out with your phone number.",
              detail: "That number becomes the key to your paid access.",
            },
            {
              label: "03",
              title: "Call from that number.",
              detail: "The AI Cardology reader recognizes your access and begins.",
            },
          ].map((step) => (
            <div key={step.label} className="border-t border-brand-line pt-4">
              <p className="font-serif text-lg text-brand-bronze">{step.label}</p>
              <h3 className="type-h3 mt-2 text-brand-ink">{step.title}</h3>
              <p className="mt-2 text-[0.95rem] leading-relaxed text-brand-ink-soft">{step.detail}</p>
            </div>
          ))}
        </div>
      </section>

      {/* 5 — Straight terms and fair use */}
      <section className="mt-16 border-t border-brand-line pt-8">
        <Kicker>Straight terms</Kicker>
        <div className="mt-5 grid gap-8 lg:grid-cols-2">
          <div className="max-w-[38em] space-y-4 text-[0.95rem] leading-relaxed text-brand-ink-soft">
            <p>
              Every reading is delivered by an AI voice reader. The Quick
              Question and Complete Reading each cover one paid session, started
              within 30 days of purchase. Access is tied to the phone number
              used at checkout.
            </p>
            <p>
              Cardology is an esoteric reflection framework — not medical,
              legal, financial, or psychological advice, and no outcome is
              guaranteed. Read the{" "}
              <Link href="/terms-of-service" className="editorial-link text-brand-ink">
                terms of service
              </Link>{" "}
              or the{" "}
              <Link href="/refund-policy" className="editorial-link text-brand-ink">
                refund policy
              </Link>
              .
            </p>
          </div>
          <div className="max-w-[38em] space-y-4 text-[0.95rem] leading-relaxed text-brand-ink-soft">
            <p className="font-serif text-lg text-brand-ink">Season Pass fair use</p>
            <p>{FAIR_USE_COPY}</p>
          </div>
        </div>
      </section>

      {/* 6 — FAQs */}
      <section className="mt-16 border-t border-brand-line pt-8">
        <h2 className="type-h2 text-brand-ink">Frequently asked questions</h2>
        <div className="mt-6 divide-y divide-brand-line">
          {visibleFaqs.map((faq) => (
            <div key={faq.q} className="py-5">
              <h3 className="type-h3 text-brand-ink">{faq.q}</h3>
              <p className="mt-2 max-w-[38em] text-[0.95rem] leading-relaxed text-brand-ink-soft">
                {faq.a}
              </p>
            </div>
          ))}
        </div>
      </section>

      {/* 7 — Final CTA */}
      <section className="shell-ink mt-16 rounded-[3px] px-6 py-12 text-center sm:px-10 sm:py-16">
        <h2 className="type-h2">Still deciding? Hear it first.</h2>
        <p className="mt-4 text-brand-on-dark-soft">
          The first card is free — call with your birthday.
        </p>
        <div className="mt-7">
          <LinkButton href={READER_PHONE_TEL} variant="accent" size="large">
            Hear Your First Card Free
          </LinkButton>
        </div>
        <p className="mt-5">
          <a
            href={READER_PHONE_TEL}
            className="font-serif text-xl text-brand-on-dark transition hover:text-brand-gold"
          >
            {READER_PHONE_DISPLAY}
          </a>
        </p>
      </section>

      <MobileActionBar readingHref="#pricing" />
    </SeoShell>
  );
}
