import type { Metadata } from "next";
import Link from "next/link";

import { SeoShell } from "@/components/seo/SeoShell";
import { Kicker, LinkButton, PricingCard } from "@/components/ui";
import {
  FAIR_USE_COPY,
  FREE_PREVIEW_BLURB,
  MICROTRUST_LINE,
  READER_PHONE_DISPLAY,
  READER_PHONE_TEL,
  SEASON_PASS_CLARIFIER,
} from "@/lib/offers";
import {
  INSTANT_REPORT_PRODUCTS,
  READING_OFFERS,
  instantReportFacts,
} from "@/lib/products";
import { CONTACT_EMAIL, SITE_NAME, SITE_URL } from "@/lib/site";

export const dynamic = "force-static";

export const metadata: Metadata = {
  title: "Personal Card Blueprint & Cardology Voice Readings",
  description:
    "Choose the $29 instant Personal Card Blueprint or compare optional AI Cardology voice readings by phone at $19, $39, and $199.",
  alternates: { canonical: "/readings" },
  openGraph: {
    siteName: SITE_NAME,
    title: "Personal Card Blueprint & Cardology Readings",
    description:
      "Start with the $29 instant Personal Card Blueprint, or talk it through with one of three AI voice-reading options.",
    url: "/readings",
    type: "website",
    images: [{ url: "/og/default.png", width: 1200, height: 630, alt: "Card Blueprints" }],
  },
};

const visibleFaqs = [
  {
    q: "Is the reader AI?",
    a: "Yes. Every reading on this line is delivered by an AI voice reader, not a human. The birth-card calculation underneath it is deterministic — the same birthday always produces the same card — while the spoken conversation is generated by AI and can make mistakes.",
  },
  {
    q: "What information do I need?",
    a: "Bring a birth date — yours, or the person the question is about. For relationship questions, bring both birthdays. Stripe Checkout asks for your email, phone number, and payment details; Card Blueprints does not require a site account.",
  },
  {
    q: "Will the reader ask for my payment card details?",
    a: "No. Stripe handles payment during checkout. The AI reader never accepts payment card details by voice, so do not say them during a call.",
  },
  {
    q: "What counts as a paid session?",
    a: "A completed paid call. The Quick Question and Complete Reading each include one paid session. Call from the phone number you used at checkout so the reader recognizes your access. If the line fails to connect or ends before the reading begins, call again from that same number.",
  },
  {
    q: "What if my purchase is not recognized or a call disconnects?",
    a: `Paid access begins after successful checkout and phone-number recognition, which can take a moment. Call again from the checkout number. If the purchase still is not recognized, or a paid reading is interrupted, email ${CONTACT_EMAIL} with the purchase email and offer name so we can help.`,
  },
  {
    q: "What does unlimited mean on the Season Pass?",
    a: `Unlimited personal return calls for 90 days, subject to fair use: ${FAIR_USE_COPY.charAt(0).toLowerCase()}${FAIR_USE_COPY.slice(1)}`,
  },
  {
    q: "Does the 90-Day Season Pass automatically renew?",
    a: "No. The Season Pass is a single one-time payment. When the 90 days end, access simply ends — there is no subscription and nothing to cancel.",
  },
  {
    q: "What is the refund policy?",
    a: "Voice access can be refunded in full before your first paid session is used. After paid usage begins, refunds are limited and reviewed fairly — if the line did not work or access was not recognized, contact us and we will make it right. See the refund policy for details.",
  },
];

export default function ReadingsPage() {
  const blueprint = INSTANT_REPORT_PRODUCTS[0];
  const paidOffers = [blueprint, ...READING_OFFERS];
  const jsonLd = [
    {
      "@context": "https://schema.org",
      "@type": "CollectionPage",
      name: "Card Blueprints paid readings and reports",
      description: metadata.description,
      url: `${SITE_URL}/readings`,
      publisher: { "@id": `${SITE_URL}/#organization` },
      mainEntity: {
        "@type": "ItemList",
        itemListElement: paidOffers.map((offer, index) => ({
          "@type": "ListItem",
          position: index + 1,
          name: offer.name,
          url: offer.kind === "instant_report"
            ? `${SITE_URL}/products/${offer.slug}`
            : `${SITE_URL}/readings#${offer.slug}`,
        })),
      },
    },
    {
      "@context": "https://schema.org",
      "@type": "FAQPage",
      mainEntity: visibleFaqs.map((faq) => ({
        "@type": "Question",
        name: faq.q,
        acceptedAnswer: { "@type": "Answer", text: faq.a },
      })),
    },
  ];

  return (
    <SeoShell crumb={[{ label: "Home", href: "/" }, { label: "Readings", href: "/readings" }]}>
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }} />

      {/* 1 — Product overview */}
      <header className="pb-10">
        <Kicker className="mb-4">Personal reports &middot; optional voice readings</Kicker>
        <h1 className="type-display max-w-[44rem] text-brand-ink">
          Get the pattern in writing, or talk it through.
        </h1>
        <p className="type-body-lg mt-6 max-w-[38em] text-brand-ink-soft">
          The Personal Card Blueprint is the flagship: an instant written
          report from your birthday. The three phone offers remain available
          when you want a live AI conversation.
        </p>
      </header>

      {/* 2 — Flagship written report */}
      <section className="border-y border-brand-line bg-brand-paper-deep px-5 py-8 sm:px-8">
        <div className="grid gap-8 lg:grid-cols-[minmax(0,1fr)_minmax(18rem,0.7fr)] lg:items-start">
          <div>
            <Kicker>Flagship &middot; instant report</Kicker>
            <h2 className="type-h2 mt-4 text-brand-ink">{blueprint.name} — {blueprint.priceLabel}</h2>
            <p className="mt-4 max-w-[38em] leading-relaxed text-brand-ink-soft">
              {blueprint.oneLine} No phone call, appointment, or subscription.
            </p>
            <ul className="mt-5 space-y-2 text-sm text-brand-ink-soft">
              {blueprint.includes.map((item) => <li key={item}>• {item}</li>)}
            </ul>
            <div className="mt-6">
              <LinkButton href={blueprint.href!} variant="accent" size="large">
                {blueprint.cta}
              </LinkButton>
            </div>
          </div>
          <dl>
            {instantReportFacts(blueprint).map((fact) => (
              <div key={fact.label} className="border-t border-brand-line py-3">
                <dt className="text-xs font-semibold uppercase tracking-[0.12em] text-brand-ink-faint">{fact.label}</dt>
                <dd className="mt-1 text-sm leading-relaxed text-brand-ink-soft">{fact.value}</dd>
              </div>
            ))}
          </dl>
        </div>
      </section>

      {/* 3 — Three voice pricing cards */}
      <section id="pricing" className="mt-12">
        <Kicker>AI voice readings &middot; by phone</Kicker>
        <h2 className="type-h2 mt-4 text-brand-ink">Compare the three voice options.</h2>
        <div className="mt-8 grid gap-5 lg:grid-cols-3">
          {READING_OFFERS.map((offer) => (
            <PricingCard
              key={offer.slug}
              offer={offer}
              emphasized={offer.slug === "complete-reading"}
            />
          ))}
        </div>
        <div className="mt-6 space-y-1 text-center text-xs leading-relaxed text-brand-ink-soft">
          <p>{MICROTRUST_LINE}</p>
          <p>{SEASON_PASS_CLARIFIER}</p>
        </div>
      </section>

      {/* 3 — Free-preview callout */}
      <section className="mt-14 border-y border-brand-line py-7">
        <div className="grid gap-5 sm:grid-cols-[1fr_auto] sm:items-center">
          <div>
            <h2 className="type-h3 text-brand-ink">Want to hear the reader first?</h2>
            <p className="mt-2 max-w-[38em] text-sm leading-relaxed text-brand-ink-soft">
              {FREE_PREVIEW_BLURB}
            </p>
            <p className="mt-3 text-sm">
              <Link href="/try" className="editorial-link text-brand-ink">
                How the free preview works &rarr;
              </Link>
            </p>
          </div>
          <LinkButton href={READER_PHONE_TEL} variant="primary" size="large">
            Call Free: {READER_PHONE_DISPLAY}
          </LinkButton>
        </div>
      </section>

      {/* 4 — How it works */}
      <section className="mt-16">
        <Kicker>How it works</Kicker>
        <h2 className="type-h2 mt-4 text-brand-ink">From checkout to conversation.</h2>
        <div className="mt-6 grid gap-8 lg:grid-cols-3">
          {[
            {
              label: "01",
              title: "Choose your reading.",
              detail: "Pick one focused question, a complete reading, or ongoing seasonal access.",
            },
            {
              label: "02",
              title: "Check out with your phone number.",
              detail: "That number becomes the key to your paid access.",
            },
            {
              label: "03",
              title: "Call from that number.",
              detail: "The AI Cardology reader recognizes your access and begins.",
            },
          ].map((step) => (
            <div key={step.label} className="border-t border-brand-line pt-4">
              <p className="font-serif text-lg text-brand-bronze">{step.label}</p>
              <h3 className="type-h3 mt-2 text-brand-ink">{step.title}</h3>
              <p className="mt-2 text-[0.95rem] leading-relaxed text-brand-ink-soft">{step.detail}</p>
            </div>
          ))}
        </div>
      </section>

      {/* 5 — Call handoff and recovery */}
      <section className="mt-16 border-y border-brand-line py-8">
        <Kicker>Before you call</Kicker>
        <h2 className="type-h2 mt-4 text-brand-ink">Your phone number is the access key.</h2>
        <div className="mt-7 divide-y divide-brand-line border-y border-brand-line">
          {[
            {
              title: "Use the checkout number.",
              detail: `After successful checkout, call ${READER_PHONE_DISPLAY} from the same phone number you entered. Paid access begins when the line recognizes that number.`,
            },
            {
              title: "Keep payment in checkout.",
              detail:
                "Stripe handles the payment before the call. The AI reader never accepts payment card details by voice.",
            },
            {
              title: "If recognition is delayed or the call drops.",
              detail: `Wait a moment and call again from the checkout number. If access still is not recognized, or a paid reading is interrupted, email ${CONTACT_EMAIL} with the purchase email and offer name.`,
            },
          ].map((item) => (
            <div key={item.title} className="grid gap-2 py-5 sm:grid-cols-[minmax(0,15rem)_1fr] sm:gap-8">
              <h3 className="type-h3 text-brand-ink">{item.title}</h3>
              <p className="max-w-[38em] text-[0.95rem] leading-relaxed text-brand-ink-soft">
                {item.detail}
              </p>
            </div>
          ))}
        </div>
      </section>

      {/* 6 — Straight terms and fair use */}
      <section className="mt-16 border-t border-brand-line pt-8">
        <Kicker>Straight terms</Kicker>
        <div className="mt-5 grid gap-8 lg:grid-cols-2">
          <div className="max-w-[38em] space-y-4 text-[0.95rem] leading-relaxed text-brand-ink-soft">
            <p>
              Every voice reading is delivered by an AI voice reader. The Quick
              Question and Complete Reading each cover one paid session, started
              within 30 days of purchase. Access is tied to the phone number
              used at checkout.
            </p>
            <p>
              Cardology is an esoteric reflection framework — not medical,
              legal, financial, or psychological advice, and no outcome is
              guaranteed. Read the{" "}
              <Link href="/terms-of-service" className="editorial-link text-brand-ink">
                terms of service
              </Link>{" "}
              or the{" "}
              <Link href="/refund-policy" className="editorial-link text-brand-ink">
                refund policy
              </Link>
              .
            </p>
          </div>
          <div className="max-w-[38em] space-y-4 text-[0.95rem] leading-relaxed text-brand-ink-soft">
            <p className="font-serif text-lg text-brand-ink">Season Pass fair use</p>
            <p>{FAIR_USE_COPY}</p>
          </div>
        </div>
      </section>

      {/* 7 — FAQs */}
      <section className="mt-16 border-t border-brand-line pt-8">
        <h2 className="type-h2 text-brand-ink">Frequently asked questions</h2>
        <div className="mt-6 divide-y divide-brand-line">
          {visibleFaqs.map((faq) => (
            <div key={faq.q} className="py-5">
              <h3 className="type-h3 text-brand-ink">{faq.q}</h3>
              <p className="mt-2 max-w-[38em] text-[0.95rem] leading-relaxed text-brand-ink-soft">
                {faq.a}
              </p>
            </div>
          ))}
        </div>
      </section>

      {/* 8 — Final CTA */}
      <section className="shell-ink mt-16 rounded-[3px] px-6 py-12 text-center sm:px-10 sm:py-16">
        <h2 className="type-h2">Still deciding? Hear it first.</h2>
        <p className="mt-4 text-brand-on-dark-soft">
          The first card is free — call with your birthday.
        </p>
        <div className="mt-7">
          <LinkButton href={READER_PHONE_TEL} variant="accent" size="large">
            Hear Your First Card Free
          </LinkButton>
        </div>
        <p className="mt-5">
          <a
            href={READER_PHONE_TEL}
            className="font-serif text-xl text-brand-on-dark transition hover:text-brand-gold"
          >
            {READER_PHONE_DISPLAY}
          </a>
        </p>
      </section>

    </SeoShell>
  );
}
