"""Known sitting US governor identifiers — not birth dates.

Sitting identity comes from Wikipedia's list of current United States
governors (50 states; no DC/territories). Dates always come from Wikidata
P569 at day precision and must match the list's birth-date template.
Do not invent extras.
"""

from __future__ import annotations

WIKIPEDIA_LIST_TITLE = "List_of_current_United_States_governors"
WIKIPEDIA_LIST_URL = (
    "https://en.wikipedia.org/wiki/List_of_current_United_States_governors"
)
BALLOTPEDIA_ROSTER_URL = "https://ballotpedia.org/Governor_(state_executive)"
NGA_ROSTER_URL = "https://www.nga.org/governors/"

# Alphabetical by state. QIDs and enwiki titles are identifiers only.
SITTING_GOVERNORS: tuple[dict[str, str], ...] = (
    {
        "state": "Alabama",
        "state_slug": "alabama",
        "postal": "AL",
        "name": "Kay Ivey",
        "slug": "kay-ivey",
        "qid": "Q6380211",
        "enwiki_title": "Kay Ivey",
    },
    {
        "state": "Alaska",
        "state_slug": "alaska",
        "postal": "AK",
        "name": "Mike Dunleavy",
        "slug": "mike-dunleavy",
        "qid": "Q16209663",
        "enwiki_title": "Mike Dunleavy (politician)",
    },
    {
        "state": "Arizona",
        "state_slug": "arizona",
        "postal": "AZ",
        "name": "Katie Hobbs",
        "slug": "katie-hobbs",
        "qid": "Q16226012",
        "enwiki_title": "Katie Hobbs",
    },
    {
        "state": "Arkansas",
        "state_slug": "arkansas",
        "postal": "AR",
        "name": "Sarah Huckabee Sanders",
        "slug": "sarah-huckabee-sanders",
        "qid": "Q27986907",
        "enwiki_title": "Sarah Huckabee Sanders",
    },
    {
        "state": "California",
        "state_slug": "california",
        "postal": "CA",
        "name": "Gavin Newsom",
        "slug": "gavin-newsom",
        "qid": "Q461391",
        "enwiki_title": "Gavin Newsom",
    },
    {
        "state": "Colorado",
        "state_slug": "colorado",
        "postal": "CO",
        "name": "Jared Polis",
        "slug": "jared-polis",
        "qid": "Q935734",
        "enwiki_title": "Jared Polis",
    },
    {
        "state": "Connecticut",
        "state_slug": "connecticut",
        "postal": "CT",
        "name": "Ned Lamont",
        "slug": "ned-lamont",
        "qid": "Q1973878",
        "enwiki_title": "Ned Lamont",
    },
    {
        "state": "Delaware",
        "state_slug": "delaware",
        "postal": "DE",
        "name": "Matt Meyer",
        "slug": "matt-meyer",
        "qid": "Q26703331",
        "enwiki_title": "Matt Meyer",
    },
    {
        "state": "Florida",
        "state_slug": "florida",
        "postal": "FL",
        "name": "Ron DeSantis",
        "slug": "ron-desantis",
        "qid": "Q3105215",
        "enwiki_title": "Ron DeSantis",
    },
    {
        "state": "Georgia",
        "state_slug": "georgia",
        "postal": "GA",
        "name": "Brian Kemp",
        "slug": "brian-kemp",
        "qid": "Q4964973",
        "enwiki_title": "Brian Kemp",
    },
    {
        "state": "Hawaii",
        "state_slug": "hawaii",
        "postal": "HI",
        "name": "Josh Green",
        "slug": "josh-green",
        "qid": "Q16224583",
        "enwiki_title": "Josh Green (politician)",
    },
    {
        "state": "Idaho",
        "state_slug": "idaho",
        "postal": "ID",
        "name": "Brad Little",
        "slug": "brad-little",
        "qid": "Q4954097",
        "enwiki_title": "Brad Little",
    },
    {
        "state": "Illinois",
        "state_slug": "illinois",
        "postal": "IL",
        "name": "JB Pritzker",
        "slug": "jb-pritzker",
        "qid": "Q6103950",
        "enwiki_title": "JB Pritzker",
    },
    {
        "state": "Indiana",
        "state_slug": "indiana",
        "postal": "IN",
        "name": "Mike Braun",
        "slug": "mike-braun",
        "qid": "Q42804470",
        "enwiki_title": "Mike Braun",
    },
    {
        "state": "Iowa",
        "state_slug": "iowa",
        "postal": "IA",
        "name": "Kim Reynolds",
        "slug": "kim-reynolds",
        "qid": "Q6409269",
        "enwiki_title": "Kim Reynolds",
    },
    {
        "state": "Kansas",
        "state_slug": "kansas",
        "postal": "KS",
        "name": "Laura Kelly",
        "slug": "laura-kelly",
        "qid": "Q6499080",
        "enwiki_title": "Laura Kelly",
    },
    {
        "state": "Kentucky",
        "state_slug": "kentucky",
        "postal": "KY",
        "name": "Andy Beshear",
        "slug": "andy-beshear",
        "qid": "Q21572825",
        "enwiki_title": "Andy Beshear",
    },
    {
        "state": "Louisiana",
        "state_slug": "louisiana",
        "postal": "LA",
        "name": "Jeff Landry",
        "slug": "jeff-landry",
        "qid": "Q1686330",
        "enwiki_title": "Jeff Landry",
    },
    {
        "state": "Maine",
        "state_slug": "maine",
        "postal": "ME",
        "name": "Janet Mills",
        "slug": "janet-mills",
        "qid": "Q6153618",
        "enwiki_title": "Janet Mills",
    },
    {
        "state": "Maryland",
        "state_slug": "maryland",
        "postal": "MD",
        "name": "Wes Moore",
        "slug": "wes-moore",
        "qid": "Q7983732",
        "enwiki_title": "Wes Moore",
    },
    {
        "state": "Massachusetts",
        "state_slug": "massachusetts",
        "postal": "MA",
        "name": "Maura Healey",
        "slug": "maura-healey",
        "qid": "Q16205062",
        "enwiki_title": "Maura Healey",
    },
    {
        "state": "Michigan",
        "state_slug": "michigan",
        "postal": "MI",
        "name": "Gretchen Whitmer",
        "slug": "gretchen-whitmer",
        "qid": "Q5607720",
        "enwiki_title": "Gretchen Whitmer",
    },
    {
        "state": "Minnesota",
        "state_slug": "minnesota",
        "postal": "MN",
        "name": "Tim Walz",
        "slug": "tim-walz",
        "qid": "Q2434360",
        "enwiki_title": "Tim Walz",
    },
    {
        "state": "Mississippi",
        "state_slug": "mississippi",
        "postal": "MS",
        "name": "Tate Reeves",
        "slug": "tate-reeves",
        "qid": "Q7687964",
        "enwiki_title": "Tate Reeves",
    },
    {
        "state": "Missouri",
        "state_slug": "missouri",
        "postal": "MO",
        "name": "Mike Kehoe",
        "slug": "mike-kehoe",
        "qid": "Q6847475",
        "enwiki_title": "Mike Kehoe",
    },
    {
        "state": "Montana",
        "state_slug": "montana",
        "postal": "MT",
        "name": "Greg Gianforte",
        "slug": "greg-gianforte",
        "qid": "Q5605607",
        "enwiki_title": "Greg Gianforte",
    },
    {
        "state": "Nebraska",
        "state_slug": "nebraska",
        "postal": "NE",
        "name": "Jim Pillen",
        "slug": "jim-pillen",
        "qid": "Q111961602",
        "enwiki_title": "Jim Pillen",
    },
    {
        "state": "Nevada",
        "state_slug": "nevada",
        "postal": "NV",
        "name": "Joe Lombardo",
        "slug": "joe-lombardo",
        "qid": "Q28033703",
        "enwiki_title": "Joe Lombardo",
    },
    {
        "state": "New Hampshire",
        "state_slug": "new-hampshire",
        "postal": "NH",
        "name": "Kelly Ayotte",
        "slug": "kelly-ayotte",
        "qid": "Q22354",
        "enwiki_title": "Kelly Ayotte",
    },
    {
        "state": "New Jersey",
        "state_slug": "new-jersey",
        "postal": "NJ",
        "name": "Mikie Sherrill",
        "slug": "mikie-sherrill",
        "qid": "Q47087146",
        "enwiki_title": "Mikie Sherrill",
    },
    {
        "state": "New Mexico",
        "state_slug": "new-mexico",
        "postal": "NM",
        "name": "Michelle Lujan Grisham",
        "slug": "michelle-lujan-grisham",
        "qid": "Q3917203",
        "enwiki_title": "Michelle Lujan Grisham",
    },
    {
        "state": "New York",
        "state_slug": "new-york",
        "postal": "NY",
        "name": "Kathy Hochul",
        "slug": "kathy-hochul",
        "qid": "Q45956",
        "enwiki_title": "Kathy Hochul",
    },
    {
        "state": "North Carolina",
        "state_slug": "north-carolina",
        "postal": "NC",
        "name": "Josh Stein",
        "slug": "josh-stein",
        "qid": "Q6289402",
        "enwiki_title": "Josh Stein",
    },
    {
        "state": "North Dakota",
        "state_slug": "north-dakota",
        "postal": "ND",
        "name": "Kelly Armstrong",
        "slug": "kelly-armstrong",
        "qid": "Q50362353",
        "enwiki_title": "Kelly Armstrong",
    },
    {
        "state": "Ohio",
        "state_slug": "ohio",
        "postal": "OH",
        "name": "Mike DeWine",
        "slug": "mike-dewine",
        "qid": "Q1363468",
        "enwiki_title": "Mike DeWine",
    },
    {
        "state": "Oklahoma",
        "state_slug": "oklahoma",
        "postal": "OK",
        "name": "Kevin Stitt",
        "slug": "kevin-stitt",
        "qid": "Q58322517",
        "enwiki_title": "Kevin Stitt",
    },
    {
        "state": "Oregon",
        "state_slug": "oregon",
        "postal": "OR",
        "name": "Tina Kotek",
        "slug": "tina-kotek",
        "qid": "Q1452454",
        "enwiki_title": "Tina Kotek",
    },
    {
        "state": "Pennsylvania",
        "state_slug": "pennsylvania",
        "postal": "PA",
        "name": "Josh Shapiro",
        "slug": "josh-shapiro",
        "qid": "Q6289368",
        "enwiki_title": "Josh Shapiro",
    },
    {
        "state": "Rhode Island",
        "state_slug": "rhode-island",
        "postal": "RI",
        "name": "Dan McKee",
        "slug": "dan-mckee",
        "qid": "Q5218111",
        "enwiki_title": "Dan McKee",
    },
    {
        "state": "South Carolina",
        "state_slug": "south-carolina",
        "postal": "SC",
        "name": "Henry McMaster",
        "slug": "henry-mcmaster",
        "qid": "Q5725737",
        "enwiki_title": "Henry McMaster",
    },
    {
        "state": "South Dakota",
        "state_slug": "south-dakota",
        "postal": "SD",
        "name": "Larry Rhoden",
        "slug": "larry-rhoden",
        "qid": "Q16193325",
        "enwiki_title": "Larry Rhoden",
    },
    {
        "state": "Tennessee",
        "state_slug": "tennessee",
        "postal": "TN",
        "name": "Bill Lee",
        "slug": "bill-lee",
        "qid": "Q58321685",
        "enwiki_title": "Bill Lee (Tennessee politician)",
    },
    {
        "state": "Texas",
        "state_slug": "texas",
        "postal": "TX",
        "name": "Greg Abbott",
        "slug": "greg-abbott",
        "qid": "Q5605224",
        "enwiki_title": "Greg Abbott",
    },
    {
        "state": "Utah",
        "state_slug": "utah",
        "postal": "UT",
        "name": "Spencer Cox",
        "slug": "spencer-cox",
        "qid": "Q16208237",
        "enwiki_title": "Spencer Cox",
    },
    {
        "state": "Vermont",
        "state_slug": "vermont",
        "postal": "VT",
        "name": "Phil Scott",
        "slug": "phil-scott",
        "qid": "Q7185808",
        "enwiki_title": "Phil Scott",
    },
    {
        "state": "Virginia",
        "state_slug": "virginia",
        "postal": "VA",
        "name": "Abigail Spanberger",
        "slug": "abigail-spanberger",
        "qid": "Q55603085",
        "enwiki_title": "Abigail Spanberger",
    },
    {
        "state": "Washington",
        "state_slug": "washington",
        "postal": "WA",
        "name": "Bob Ferguson",
        "slug": "bob-ferguson",
        "qid": "Q4932411",
        "enwiki_title": "Bob Ferguson (politician)",
    },
    {
        "state": "West Virginia",
        "state_slug": "west-virginia",
        "postal": "WV",
        "name": "Patrick Morrisey",
        "slug": "patrick-morrisey",
        "qid": "Q7147254",
        "enwiki_title": "Patrick Morrisey",
    },
    {
        "state": "Wisconsin",
        "state_slug": "wisconsin",
        "postal": "WI",
        "name": "Tony Evers",
        "slug": "tony-evers",
        "qid": "Q7822309",
        "enwiki_title": "Tony Evers",
    },
    {
        "state": "Wyoming",
        "state_slug": "wyoming",
        "postal": "WY",
        "name": "Mark Gordon",
        "slug": "mark-gordon",
        "qid": "Q6767775",
        "enwiki_title": "Mark Gordon",
    },
)

SITTING_QIDS: tuple[str, ...] = tuple(row["qid"] for row in SITTING_GOVERNORS)
SITTING_SLUGS: tuple[str, ...] = tuple(row["slug"] for row in SITTING_GOVERNORS)
SITTING_STATES: tuple[str, ...] = tuple(row["state"] for row in SITTING_GOVERNORS)
SITTING_BY_STATE: dict[str, dict[str, str]] = {row["state"]: row for row in SITTING_GOVERNORS}
