"""Known US House leadership + standing-chair identifiers — not birth dates.

Sitting identity comes from house.gov/leadership (elected party leadership)
and unitedstates/congress-legislators committee-membership-current.json
(standing committee chairs only). Select and campaign committees are out
of scope. Dates always come from day-precision public sources at harvest
time and must agree. Do not invent extras or days.
"""

from __future__ import annotations

HOUSE_LEADERSHIP_URL = "https://www.house.gov/leadership"
HOUSE_COMMITTEES_URL = "https://www.house.gov/committees"
LEGISLATORS_URL = (
    "https://raw.githubusercontent.com/unitedstates/congress-legislators/"
    "gh-pages/legislators-current.json"
)
COMMITTEE_MEMBERSHIP_URL = (
    "https://raw.githubusercontent.com/unitedstates/congress-legislators/"
    "gh-pages/committee-membership-current.json"
)
COMMITTEES_YAML_URL = (
    "https://raw.githubusercontent.com/unitedstates/congress-legislators/"
    "main/committees-current.yaml"
)
HISTORY_HOUSE_BIOGUIDE_URL = "https://history.house.gov/People/Search/"
BIOGUIDE_BIO_URL = "https://bioguide.congress.gov/search/bio/{bioguide}"

# Standing House committees only. Select / campaign / joint are omitted.
STANDING_COMMITTEES: dict[str, str] = {
    "HSAG": "Agriculture",
    "HSAP": "Appropriations",
    "HSAS": "Armed Services",
    "HSBU": "Budget",
    "HSED": "Education and Workforce",
    "HSIF": "Energy and Commerce",
    "HSSO": "Ethics",
    "HSBA": "Financial Services",
    "HSFA": "Foreign Affairs",
    "HSHM": "Homeland Security",
    "HSHA": "House Administration",
    "HSJU": "Judiciary",
    "HSII": "Natural Resources",
    "HSGO": "Oversight and Government Reform",
    "HSRU": "Rules",
    "HSSY": "Science, Space, and Technology",
    "HSSM": "Small Business",
    "HSPW": "Transportation and Infrastructure",
    "HSVR": "Veterans' Affairs",
    "HSWM": "Ways and Means",
}

# Documented out of scope — never cataloged, never given a page.
OUT_OF_SCOPE_COMMITTEES: dict[str, str] = {
    "HLIG": "House Permanent Select Committee on Intelligence",
    "HSZS": (
        "House Select Committee on the Strategic Competition Between "
        "the United States and the Chinese Communist Party"
    ),
    "HSQJ": (
        "House Select Subcommittee to Investigate the Remaining Questions "
        "Surrounding January 6, 2021"
    ),
}

POSTAL_TO_STATE: dict[str, str] = {
    "AL": "Alabama",
    "AK": "Alaska",
    "AZ": "Arizona",
    "AR": "Arkansas",
    "CA": "California",
    "CO": "Colorado",
    "CT": "Connecticut",
    "DE": "Delaware",
    "FL": "Florida",
    "GA": "Georgia",
    "HI": "Hawaii",
    "ID": "Idaho",
    "IL": "Illinois",
    "IN": "Indiana",
    "IA": "Iowa",
    "KS": "Kansas",
    "KY": "Kentucky",
    "LA": "Louisiana",
    "ME": "Maine",
    "MD": "Maryland",
    "MA": "Massachusetts",
    "MI": "Michigan",
    "MN": "Minnesota",
    "MS": "Mississippi",
    "MO": "Missouri",
    "MT": "Montana",
    "NE": "Nebraska",
    "NV": "Nevada",
    "NH": "New Hampshire",
    "NJ": "New Jersey",
    "NM": "New Mexico",
    "NY": "New York",
    "NC": "North Carolina",
    "ND": "North Dakota",
    "OH": "Ohio",
    "OK": "Oklahoma",
    "OR": "Oregon",
    "PA": "Pennsylvania",
    "RI": "Rhode Island",
    "SC": "South Carolina",
    "SD": "South Dakota",
    "TN": "Tennessee",
    "TX": "Texas",
    "UT": "Utah",
    "VT": "Vermont",
    "VA": "Virginia",
    "WA": "Washington",
    "WV": "West Virginia",
    "WI": "Wisconsin",
    "WY": "Wyoming",
}

# house.gov/leadership order, then standing chairs A–Z by committee.
# QIDs / Bioguide / titles are identifiers only. No birth dates here.
HOUSE_CHAIRS: tuple[dict[str, object], ...] = (
    {
        "office_id": "speaker",
        "office": "Speaker of the House",
        "role_kind": "leadership",
        "sort_order": 1,
        "name": "Mike Johnson",
        "slug": "mike-johnson",
        "qid": "Q19880665",
        "bioguide": "J000299",
        "enwiki_title": "Mike Johnson",
        "house_gov_name": "Mike Johnson",
        "party": "Republican",
        "postal": "LA",
        "district": 4,
        "committee_thomas_id": None,
    },
    {
        "office_id": "majority-leader",
        "office": "Majority Leader",
        "role_kind": "leadership",
        "sort_order": 2,
        "name": "Steve Scalise",
        "slug": "steve-scalise",
        "qid": "Q1857141",
        "bioguide": "S001176",
        "enwiki_title": "Steve Scalise",
        "house_gov_name": "Steve Scalise",
        "party": "Republican",
        "postal": "LA",
        "district": 1,
        "committee_thomas_id": None,
    },
    {
        "office_id": "majority-whip",
        "office": "Majority Whip",
        "role_kind": "leadership",
        "sort_order": 3,
        "name": "Tom Emmer",
        "slug": "tom-emmer",
        "qid": "Q7815723",
        "bioguide": "E000294",
        "enwiki_title": "Tom Emmer",
        "house_gov_name": "Tom Emmer",
        "party": "Republican",
        "postal": "MN",
        "district": 6,
        "committee_thomas_id": None,
    },
    {
        "office_id": "republican-conference-chair",
        "office": "Republican Conference Chairman",
        "role_kind": "leadership",
        "sort_order": 4,
        "name": "Lisa McClain",
        "slug": "lisa-mcclain",
        "qid": "Q102184540",
        "bioguide": "M001136",
        "enwiki_title": "Lisa McClain",
        "house_gov_name": "Lisa McClain",
        "party": "Republican",
        "postal": "MI",
        "district": 9,
        "committee_thomas_id": None,
    },
    {
        "office_id": "republican-policy-chair",
        "office": "Republican Policy Committee Chairman",
        "role_kind": "leadership",
        "sort_order": 5,
        "name": "Jay Obernolte",
        "slug": "jay-obernolte",
        "qid": "Q16849797",
        "bioguide": "O000019",
        "enwiki_title": "Jay Obernolte",
        "house_gov_name": "Jay Obernolte",
        "party": "Republican",
        "postal": "CA",
        "district": 23,
        "committee_thomas_id": None,
    },
    {
        "office_id": "democratic-leader",
        "office": "Democratic Leader",
        "role_kind": "leadership",
        "sort_order": 6,
        "name": "Hakeem Jeffries",
        "slug": "hakeem-jeffries",
        "qid": "Q5640425",
        "bioguide": "J000294",
        "enwiki_title": "Hakeem Jeffries",
        "house_gov_name": "Hakeem Jeffries",
        "party": "Democrat",
        "postal": "NY",
        "district": 8,
        "committee_thomas_id": None,
    },
    {
        "office_id": "democratic-whip",
        "office": "Democratic Whip",
        "role_kind": "leadership",
        "sort_order": 7,
        "name": "Katherine Clark",
        "slug": "katherine-clark",
        "qid": "Q6376330",
        "bioguide": "C001101",
        "enwiki_title": "Katherine Clark",
        "house_gov_name": "Katherine Clark",
        "party": "Democrat",
        "postal": "MA",
        "district": 5,
        "committee_thomas_id": None,
    },
    {
        "office_id": "democratic-caucus-chair",
        "office": "Democratic Caucus Chairman",
        "role_kind": "leadership",
        "sort_order": 8,
        "name": "Pete Aguilar",
        "slug": "pete-aguilar",
        "qid": "Q7171821",
        "bioguide": "A000371",
        "enwiki_title": "Pete Aguilar",
        "house_gov_name": "Pete Aguilar",
        "party": "Democrat",
        "postal": "CA",
        "district": 33,
        "committee_thomas_id": None,
    },
    {
        "office_id": "democratic-caucus-vice-chair",
        "office": "Democratic Caucus Vice Chair",
        "role_kind": "leadership",
        "sort_order": 9,
        "name": "Ted Lieu",
        "slug": "ted-lieu",
        "qid": "Q7693450",
        "bioguide": "L000582",
        "enwiki_title": "Ted Lieu",
        "house_gov_name": "Ted Lieu",
        "party": "Democrat",
        "postal": "CA",
        "district": 36,
        "committee_thomas_id": None,
    },
    {
        "office_id": "assistant-democratic-leader",
        "office": "Assistant Democratic Leader",
        "role_kind": "leadership",
        "sort_order": 10,
        "name": "Joe Neguse",
        "slug": "joe-neguse",
        "qid": "Q57242006",
        "bioguide": "N000191",
        "enwiki_title": "Joe Neguse",
        "house_gov_name": "Joe Neguse",
        "party": "Democrat",
        "postal": "CO",
        "district": 2,
        "committee_thomas_id": None,
    },
    {
        "office_id": "agriculture",
        "office": "Chair of the House Committee on Agriculture",
        "role_kind": "chair",
        "sort_order": 11,
        "name": "Glenn Thompson",
        "slug": "glenn-thompson",
        "qid": "Q1531120",
        "bioguide": "T000467",
        "enwiki_title": "Glenn Thompson (politician)",
        "house_gov_name": "Glenn Thompson",
        "party": "Republican",
        "postal": "PA",
        "district": 15,
        "committee_thomas_id": "HSAG",
    },
    {
        "office_id": "appropriations",
        "office": "Chair of the House Committee on Appropriations",
        "role_kind": "chair",
        "sort_order": 12,
        "name": "Tom Cole",
        "slug": "tom-cole",
        "qid": "Q173839",
        "bioguide": "C001053",
        "enwiki_title": "Tom Cole",
        "house_gov_name": "Tom Cole",
        "party": "Republican",
        "postal": "OK",
        "district": 4,
        "committee_thomas_id": "HSAP",
    },
    {
        "office_id": "armed-services",
        "office": "Chair of the House Committee on Armed Services",
        "role_kind": "chair",
        "sort_order": 13,
        "name": "Mike Rogers",
        "slug": "mike-rogers",
        "qid": "Q693238",
        "bioguide": "R000575",
        "enwiki_title": "Mike Rogers (Alabama politician)",
        "house_gov_name": "Mike Rogers",
        "party": "Republican",
        "postal": "AL",
        "district": 3,
        "committee_thomas_id": "HSAS",
    },
    {
        "office_id": "budget",
        "office": "Chair of the House Committee on the Budget",
        "role_kind": "chair",
        "sort_order": 14,
        "name": "Jodey Arrington",
        "slug": "jodey-arrington",
        "qid": "Q6207815",
        "bioguide": "A000375",
        "enwiki_title": "Jodey Arrington",
        "house_gov_name": "Jodey Arrington",
        "party": "Republican",
        "postal": "TX",
        "district": 19,
        "committee_thomas_id": "HSBU",
    },
    {
        "office_id": "education-and-workforce",
        "office": "Chair of the House Committee on Education and Workforce",
        "role_kind": "chair",
        "sort_order": 15,
        "name": "Tim Walberg",
        "slug": "tim-walberg",
        "qid": "Q978618",
        "bioguide": "W000798",
        "enwiki_title": "Tim Walberg",
        "house_gov_name": "Tim Walberg",
        "party": "Republican",
        "postal": "MI",
        "district": 5,
        "committee_thomas_id": "HSED",
    },
    {
        "office_id": "energy-and-commerce",
        "office": "Chair of the House Committee on Energy and Commerce",
        "role_kind": "chair",
        "sort_order": 16,
        "name": "Brett Guthrie",
        "slug": "brett-guthrie",
        "qid": "Q910794",
        "bioguide": "G000558",
        "enwiki_title": "Brett Guthrie",
        "house_gov_name": "Brett Guthrie",
        "party": "Republican",
        "postal": "KY",
        "district": 2,
        "committee_thomas_id": "HSIF",
    },
    {
        "office_id": "ethics",
        "office": "Chair of the House Committee on Ethics",
        "role_kind": "chair",
        "sort_order": 17,
        "name": "Michael Guest",
        "slug": "michael-guest",
        "qid": "Q60428645",
        "bioguide": "G000591",
        "enwiki_title": "Michael Guest (politician)",
        "house_gov_name": "Michael Guest",
        "party": "Republican",
        "postal": "MS",
        "district": 3,
        "committee_thomas_id": "HSSO",
    },
    {
        "office_id": "financial-services",
        "office": "Chair of the House Committee on Financial Services",
        "role_kind": "chair",
        "sort_order": 18,
        "name": "French Hill",
        "slug": "french-hill",
        "qid": "Q18631366",
        "bioguide": "H001072",
        "enwiki_title": "French Hill (politician)",
        "house_gov_name": "French Hill",
        "party": "Republican",
        "postal": "AR",
        "district": 2,
        "committee_thomas_id": "HSBA",
    },
    {
        "office_id": "foreign-affairs",
        "office": "Chair of the House Committee on Foreign Affairs",
        "role_kind": "chair",
        "sort_order": 19,
        "name": "Brian Mast",
        "slug": "brian-mast",
        "qid": "Q27733854",
        "bioguide": "M001199",
        "enwiki_title": "Brian Mast",
        "house_gov_name": "Brian Mast",
        "party": "Republican",
        "postal": "FL",
        "district": 21,
        "committee_thomas_id": "HSFA",
    },
    {
        "office_id": "homeland-security",
        "office": "Chair of the House Committee on Homeland Security",
        "role_kind": "chair",
        "sort_order": 20,
        "name": "Andrew Garbarino",
        "slug": "andrew-garbarino",
        "qid": "Q21257859",
        "bioguide": "G000597",
        "enwiki_title": "Andrew Garbarino",
        "house_gov_name": "Andrew Garbarino",
        "party": "Republican",
        "postal": "NY",
        "district": 2,
        "committee_thomas_id": "HSHM",
    },
    {
        "office_id": "house-administration",
        "office": "Chair of the House Committee on House Administration",
        "role_kind": "chair",
        "sort_order": 21,
        "name": "Bryan Steil",
        "slug": "bryan-steil",
        "qid": "Q58494431",
        "bioguide": "S001213",
        "enwiki_title": "Bryan Steil",
        "house_gov_name": "Bryan Steil",
        "party": "Republican",
        "postal": "WI",
        "district": 1,
        "committee_thomas_id": "HSHA",
    },
    {
        "office_id": "judiciary",
        "office": "Chair of the House Committee on the Judiciary",
        "role_kind": "chair",
        "sort_order": 22,
        "name": "Jim Jordan",
        "slug": "jim-jordan",
        "qid": "Q186215",
        "bioguide": "J000289",
        "enwiki_title": "Jim Jordan",
        "house_gov_name": "Jim Jordan",
        "party": "Republican",
        "postal": "OH",
        "district": 4,
        "committee_thomas_id": "HSJU",
    },
    {
        "office_id": "natural-resources",
        "office": "Chair of the House Committee on Natural Resources",
        "role_kind": "chair",
        "sort_order": 23,
        "name": "Bruce Westerman",
        "slug": "bruce-westerman",
        "qid": "Q16197421",
        "bioguide": "W000821",
        "enwiki_title": "Bruce Westerman",
        "house_gov_name": "Bruce Westerman",
        "party": "Republican",
        "postal": "AR",
        "district": 4,
        "committee_thomas_id": "HSII",
    },
    {
        "office_id": "oversight",
        "office": "Chair of the House Committee on Oversight and Government Reform",
        "role_kind": "chair",
        "sort_order": 24,
        "name": "James Comer",
        "slug": "james-comer",
        "qid": "Q6131602",
        "bioguide": "C001108",
        "enwiki_title": "James Comer",
        "house_gov_name": "James Comer",
        "party": "Republican",
        "postal": "KY",
        "district": 1,
        "committee_thomas_id": "HSGO",
    },
    {
        "office_id": "rules",
        "office": "Chair of the House Committee on Rules",
        "role_kind": "chair",
        "sort_order": 25,
        "name": "Virginia Foxx",
        "slug": "virginia-foxx",
        "qid": "Q458453",
        "bioguide": "F000450",
        "enwiki_title": "Virginia Foxx",
        "house_gov_name": "Virginia Foxx",
        "party": "Republican",
        "postal": "NC",
        "district": 5,
        "committee_thomas_id": "HSRU",
    },
    {
        "office_id": "science-space-technology",
        "office": "Chair of the House Committee on Science, Space, and Technology",
        "role_kind": "chair",
        "sort_order": 26,
        "name": "Brian Babin",
        "slug": "brian-babin",
        "qid": "Q16979824",
        "bioguide": "B001291",
        "enwiki_title": "Brian Babin",
        "house_gov_name": "Brian Babin",
        "party": "Republican",
        "postal": "TX",
        "district": 36,
        "committee_thomas_id": "HSSY",
    },
    {
        "office_id": "small-business",
        "office": "Chair of the House Committee on Small Business",
        "role_kind": "chair",
        "sort_order": 27,
        "name": "Roger Williams",
        "slug": "roger-williams",
        "qid": "Q4014560",
        "bioguide": "W000816",
        "enwiki_title": "Roger Williams (Texas politician)",
        "house_gov_name": "Roger Williams",
        "party": "Republican",
        "postal": "TX",
        "district": 25,
        "committee_thomas_id": "HSSM",
    },
    {
        "office_id": "transportation",
        "office": "Chair of the House Committee on Transportation and Infrastructure",
        "role_kind": "chair",
        "sort_order": 28,
        "name": "Sam Graves",
        "slug": "sam-graves",
        "qid": "Q465638",
        "bioguide": "G000546",
        "enwiki_title": "Sam Graves",
        "house_gov_name": "Sam Graves",
        "party": "Republican",
        "postal": "MO",
        "district": 6,
        "committee_thomas_id": "HSPW",
    },
    {
        "office_id": "veterans-affairs",
        "office": "Chair of the House Committee on Veterans' Affairs",
        "role_kind": "chair",
        "sort_order": 29,
        "name": "Mike Bost",
        "slug": "mike-bost",
        "qid": "Q6846090",
        "bioguide": "B001295",
        "enwiki_title": "Mike Bost",
        "house_gov_name": "Mike Bost",
        "party": "Republican",
        "postal": "IL",
        "district": 12,
        "committee_thomas_id": "HSVR",
    },
    {
        "office_id": "ways-and-means",
        "office": "Chair of the House Committee on Ways and Means",
        "role_kind": "chair",
        "sort_order": 30,
        "name": "Jason Smith",
        "slug": "jason-smith",
        "qid": "Q6163589",
        "bioguide": "S001195",
        "enwiki_title": "Jason Smith (American politician)",
        "house_gov_name": "Jason Smith",
        "party": "Republican",
        "postal": "MO",
        "district": 8,
        "committee_thomas_id": "HSWM",
    },
)

SITTING_QIDS: tuple[str, ...] = tuple(str(row["qid"]) for row in HOUSE_CHAIRS)
SITTING_SLUGS: tuple[str, ...] = tuple(str(row["slug"]) for row in HOUSE_CHAIRS)
SITTING_BIOGUIDES: tuple[str, ...] = tuple(str(row["bioguide"]) for row in HOUSE_CHAIRS)
SITTING_OFFICE_IDS: tuple[str, ...] = tuple(str(row["office_id"]) for row in HOUSE_CHAIRS)
LEADERSHIP_ROWS: tuple[dict[str, object], ...] = tuple(
    row for row in HOUSE_CHAIRS if row["role_kind"] == "leadership"
)
CHAIR_ROWS: tuple[dict[str, object], ...] = tuple(
    row for row in HOUSE_CHAIRS if row["role_kind"] == "chair"
)
