import type { Metadata } from "next";
import Link from "next/link";

import { SeoShell } from "@/components/seo/SeoShell";
import {
  READER_PHONE_DISPLAY,
  READER_PHONE_TEL,
  TRIAL_NAME,
  TRIAL_OFFER,
} from "@/lib/offers";
import { offerBySlug, readingOfferHref } from "@/lib/products";
import { SITE_URL } from "@/lib/site";

export const dynamic = "force-static";

const PAGE_TITLE = "$9 Deck Pass Trial: 7 Days of Unlimited AI Readings";
const PAGE_DESCRIPTION =
  "Try the Card Blueprints AI reader for a week: unlimited phone readings, compatibility lookups, and daily cards. Start with a free teaser call, or skip straight to the $99 full pass.";

export const metadata: Metadata = {
  title: { absolute: `${PAGE_TITLE} | Card Blueprints` },
  description: PAGE_DESCRIPTION,
  alternates: { canonical: "/try" },
  openGraph: {
    title: PAGE_TITLE,
    description: PAGE_DESCRIPTION,
    url: "/try",
    type: "website",
  },
};

export default function TryPage() {
  const pass = offerBySlug("one-question-reading");
  const passHref = pass ? readingOfferHref(pass) : "/readings";

  const faqs = [
    {
      q: "What is the AI reader?",
      a: "An AI voice guide trained on the deterministic Cardology system. The card math comes from fixed tables — same birthday, same card, every time — while the spoken explanation is generated by AI. It answers the phone, asks your birthday, and reads from there: your birth card, what it presses on, and what the current timing is asking of you.",
    },
    {
      q: "What does 7 days of unlimited readings mean?",
      a: "For seven days you can call the reading line as often as you like: your full birth-card reading, follow-up questions, compatibility lookups for the people in your life, timing questions, and a fresh daily card every morning. No per-question fees and no appointment — the line answers when you call.",
    },
    {
      q: "How do I start the trial?",
      a: TRIAL_OFFER.trialAvailable
        ? "Check out for $9, then call the reading line from the phone number you used at checkout. The line recognizes your number and your trial starts with that first call — no codes, no confirmation emails to dig through."
        : `The $9 trial is opening to a first group of callers. Until it opens, call ${READER_PHONE_DISPLAY} free — the AI reader answers, asks your birthday, and reads your first card on the spot — or unlock the full $99 pass and skip the wait entirely.`,
    },
    {
      q: "What happens after the 7 days?",
      a: "The trial simply ends — it is a one-time $9, not a subscription, so nothing renews by itself. If you want to keep the line open, the $99 Deck Pass covers 90 days of unlimited calls, and most trial callers who use the daily card keep going.",
    },
    {
      q: "Is the free teaser call really free?",
      a: `Yes. Calling ${READER_PHONE_DISPLAY} costs nothing and needs no account or card. The AI reader gives you a first-card teaser reading so you can hear exactly what you would be unlocking before you pay anyone anything.`,
    },
  ];

  const jsonLd: object[] = [
    {
      "@context": "https://schema.org",
      "@type": "WebPage",
      name: PAGE_TITLE,
      description: PAGE_DESCRIPTION,
      url: `${SITE_URL}/try`,
      isPartOf: { "@id": `${SITE_URL}/#organization` },
    },
    {
      "@context": "https://schema.org",
      "@type": "FAQPage",
      mainEntity: faqs.map((faq) => ({
        "@type": "Question",
        name: faq.q,
        acceptedAnswer: { "@type": "Answer", text: faq.a },
      })),
    },
  ];

  // Only claim a purchasable $9 offer in structured data once it is live.
  if (TRIAL_OFFER.trialAvailable) {
    jsonLd.push({
      "@context": "https://schema.org",
      "@type": "Product",
      name: TRIAL_NAME,
      description: "Seven days of unlimited AI phone readings from the Card Blueprints reading line.",
      brand: { "@id": `${SITE_URL}/#organization` },
      url: `${SITE_URL}/try`,
      offers: {
        "@type": "Offer",
        price: 9,
        priceCurrency: "USD",
        availability: "https://schema.org/InStock",
        url: `${SITE_URL}${TRIAL_OFFER.trialCheckoutPath}`,
      },
    });
  }

  return (
    <SeoShell crumb={[{ label: "Home", href: "/" }, { label: "Deck Pass Trial", href: "/try" }]}>
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }} />

      <header className="max-w-3xl pb-8">
        <p className="oracle-eyebrow mb-4">Deck Pass Trial</p>
        <h1 className="display text-5xl leading-none text-[#14110d] sm:text-6xl">
          $9 Deck Pass Trial: 7 days of unlimited AI readings.
        </h1>
        <p className="mt-5 max-w-2xl font-serif text-xl leading-relaxed text-[#3d352d] sm:text-2xl">
          One week of the full reading line — your birth card read for your
          life, follow-up questions, compatibility lookups, and a daily card —
          for less than a deck of cards.
        </p>
        <div className="mt-6 border border-[#14110d]/15 bg-[#eadfcd]/70 p-5" data-ai-summary>
          <p className="oracle-eyebrow mb-2">Quick answer</p>
          <p className="text-base leading-relaxed text-[#3d352d]">
            The Deck Pass trial gives you 7 days of unlimited calls to the Card
            Blueprints AI reader for $9. Hear it first for free — call{" "}
            <a href={READER_PHONE_TEL} className="font-bold text-[#9e3d24] underline underline-offset-4">
              {READER_PHONE_DISPLAY}
            </a>{" "}
            and the AI reader reads your first card on the spot. Want the whole
            season instead? The $99 Deck Pass covers 90 days.
          </p>
        </div>
      </header>

      {TRIAL_OFFER.trialAvailable ? (
        <section className="border border-[#14110d]/18 bg-[#14110d] p-6 text-[#f4f0e7] sm:p-8">
          <p className="oracle-eyebrow text-[#c8bca8]">Start now</p>
          <h2 className="mt-3 max-w-2xl font-serif text-3xl leading-none sm:text-4xl">
            Seven days. Unlimited readings. One $9 payment.
          </h2>
          <p className="mt-4 max-w-2xl text-base leading-relaxed text-[#d7cdbc]">
            Check out, then call from the number you used at checkout — the
            line recognizes you and the first reading starts immediately.
          </p>
          <div className="mt-6 flex flex-col gap-3 sm:flex-row">
            <Link href={TRIAL_OFFER.trialCheckoutPath} className="paper-button large-button text-center">
              Start the 7-day trial — $9
            </Link>
            <Link href={passHref} className="border border-[#f4f0e7]/30 px-6 py-3 text-center text-sm font-bold uppercase text-[#f4f0e7] transition hover:bg-[#f4f0e7]/10">
              Skip straight to the full pass — $99
            </Link>
          </div>
          <p className="mt-4 text-xs leading-relaxed text-[#c8bca8]">
            Secure Stripe checkout. One-time payment — the trial does not renew
            by itself.
          </p>
        </section>
      ) : (
        <section className="border border-[#14110d]/18 bg-[#14110d] p-6 text-[#f4f0e7] sm:p-8">
          <p className="oracle-eyebrow text-[#c8bca8]">Opening soon — join the first callers</p>
          <h2 className="mt-3 max-w-2xl font-serif text-3xl leading-none sm:text-4xl">
            The $9 trial opens to a first group of callers. Your first card is
            already free.
          </h2>
          <p className="mt-4 max-w-2xl text-base leading-relaxed text-[#d7cdbc]">
            Don&rsquo;t wait on a checkout page. Call the reading line right
            now — the AI reader answers, asks your birthday, and reads your
            first card for $0. When the trial opens, first callers hear it on
            the line first.
          </p>
          <div className="mt-6 flex flex-col gap-3 sm:flex-row">
            <a href={READER_PHONE_TEL} className="paper-button large-button text-center">
              Call free: {READER_PHONE_DISPLAY}
            </a>
            <Link href={passHref} className="border border-[#f4f0e7]/30 px-6 py-3 text-center text-sm font-bold uppercase text-[#f4f0e7] transition hover:bg-[#f4f0e7]/10">
              Skip the wait — full pass, $99
            </Link>
          </div>
          <p className="mt-4 text-xs leading-relaxed text-[#c8bca8]">
            The teaser call is free — no account, no card. The $99 Deck Pass
            opens unlimited calls for 90 days today.
          </p>
        </section>
      )}

      <section className="mt-12 grid gap-6 lg:grid-cols-[1.05fr_0.95fr]">
        <div className="border border-[#14110d]/18 bg-[#f4f0e7]/82 p-6 shadow-[0_1.5rem_4rem_rgba(20,17,13,0.08)] sm:p-7">
          <p className="oracle-eyebrow text-[#9e3d24]">What the AI reader is</p>
          <h2 className="mt-3 font-serif text-3xl leading-none text-[#14110d]">
            A reader that answers the phone. Every time.
          </h2>
          <p className="mt-4 text-base leading-relaxed text-[#5b5148]">
            The reader on the line is an AI voice guide built on the
            deterministic Cardology system. The card math is fixed — same
            birthday, same card, every time — and the reader turns it into a
            conversation about your actual life: the person you can&rsquo;t
            figure out, the decision on the table, the pattern that keeps
            coming back.
          </p>
          <blockquote className="mt-5 border-l-2 border-[#9e3d24]/40 pl-5 font-serif text-lg leading-relaxed text-[#3d352d]">
            <p>
              &ldquo;Tell me your birthday and I&rsquo;ll show you the card
              you&rsquo;ve been playing your whole life. Then ask me anything —
              I don&rsquo;t rush, and I answer at 2 a.m.&rdquo;
            </p>
          </blockquote>
          <p className="mt-4 text-xs leading-relaxed text-[#5b5148]">
            The card lookups come from fixed tables and formulas; the spoken
            explanation is generated by AI and can make mistakes. A mirror, not
            a forecast.
          </p>
        </div>

        <div className="border border-[#14110d]/15 bg-[#eadfcd]/55 p-5 sm:p-6">
          <h2 className="font-serif text-3xl text-[#14110d]">What 7 days unlimited includes</h2>
          <ul className="mt-5 space-y-3 text-sm leading-relaxed text-[#3d352d] sm:text-base">
            <li className="border-t border-[#14110d]/12 pt-3">
              <strong>Your complete reading</strong> — birth card, ruling card,
              shadow range, and what the pattern presses on.
            </li>
            <li className="border-t border-[#14110d]/12 pt-3">
              <strong>Unlimited return calls</strong> — new questions, new
              answers, as often as you want for the full week.
            </li>
            <li className="border-t border-[#14110d]/12 pt-3">
              <strong>Compatibility lookups</strong> — bring a second birthday
              and hear where the attraction and the friction actually live.
            </li>
            <li className="border-t border-[#14110d]/12 pt-3">
              <strong>Timing and daily cards</strong> — the card active for you
              right now, fresh every morning you call.
            </li>
            <li className="border-t border-[#14110d]/12 pt-3">
              <strong>No per-question fees</strong> — the trial is the whole
              line, not a metered sample.
            </li>
          </ul>
        </div>
      </section>

      <section className="mt-12 border border-[#14110d]/15 bg-[#f4f0e7]/78 p-6 sm:p-7">
        <p className="oracle-eyebrow text-[#9e3d24]">Already sure?</p>
        <div className="mt-3 grid gap-6 lg:grid-cols-[1.1fr_0.9fr] lg:items-center">
          <div>
            <h2 className="font-serif text-3xl leading-none text-[#14110d]">
              Skip the trial — take the full Deck Pass.
            </h2>
            <p className="mt-4 text-base leading-relaxed text-[#5b5148]">
              The $99 pass is the same unlimited line for a full 90 days: the
              complete reading, every follow-up, compatibility for the people
              around you, and a daily card for a whole season. If you already
              know one week won&rsquo;t be enough, start here.
            </p>
          </div>
          <div className="flex flex-col gap-3">
            <Link href={passHref} className="ink-button large-button text-center">
              Get the $99 Deck Pass — 90 days
            </Link>
            <Link href="/readings" className="text-center text-sm font-bold uppercase text-[#9e3d24] underline underline-offset-4">
              Compare every reading →
            </Link>
          </div>
        </div>
      </section>

      <section className="mt-12 border-t border-[#14110d]/15 pt-8">
        <h2 className="font-serif text-4xl leading-none text-[#14110d]">Frequently asked questions</h2>
        <div className="mt-5 space-y-4">
          {faqs.map((faq) => (
            <div key={faq.q} className="border-t border-[#14110d]/15 pt-4">
              <h3 className="font-serif text-2xl text-[#14110d]">{faq.q}</h3>
              <p className="mt-2 text-base leading-relaxed text-[#5b5148]">{faq.a}</p>
            </div>
          ))}
        </div>
      </section>
    </SeoShell>
  );
}
