"use client";

import Link from "next/link";

import { trackClientFunnelEvent } from "@/components/analytics/AnalyticsCapture";
import {
  DEEP_DIVE_OFFER_SLUG,
  DEEP_DIVE_PRICE_LABEL,
  DEEP_DIVE_PRODUCT_NAME,
  DEEP_DIVE_PRODUCT_PATH,
} from "@/lib/deep-dive";

const POINTS = [
  "Your birth card, light read and shadow read",
  "The 52-day chapter you're in now, dated",
  "All seven chapters, and the year as one map",
] as const;

/**
 * Product still beside the free calculators: a real screen from the purchased
 * 52xSeven Blueprint (public/product/52xseven-now.png, regenerated by
 * scripts/product-still.ts). Links to the sales page, where the live preview
 * takes over — the buy button itself stays on the calculator's own result.
 */
export function ProductStill({
  placement,
  className = "",
  image = "now",
  layout = "row",
  lede,
}: {
  placement: string;
  className?: string;
  /** Which screen to show: the current chapter, or the year map. */
  image?: "now" | "story";
  /**
   * "row" — device beside the copy; needs roughly 30rem of width.
   * "stack" — device above a short line of copy; for narrow columns.
   */
  layout?: "row" | "stack";
  /** Opening line. Defaults to the single-birthday calculator framing. */
  lede?: string;
}) {
  const stacked = layout === "stack";
  const src = `/product/52xseven-${image}.png`;
  const alt =
    image === "story"
      ? `The ${DEEP_DIVE_PRODUCT_NAME} year map: seven 52-day chapters in a ring around your birth card`
      : `The ${DEEP_DIVE_PRODUCT_NAME} on a phone, showing the 52-day chapter you are in right now`;

  return (
    <aside
      className={`rounded-[3px] border border-brand-line bg-brand-ivory px-5 py-6 ${className}`}
      aria-labelledby={`product-still-${placement}`}
    >
      <p className="type-eyebrow text-brand-bronze">
        {DEEP_DIVE_PRODUCT_NAME} · {DEEP_DIVE_PRICE_LABEL}
      </p>
      <h2
        id={`product-still-${placement}`}
        className="mt-2 font-serif text-2xl leading-tight text-brand-ink"
      >
        Your whole year, on one map.
      </h2>

      <div
        className={
          stacked
            ? "mt-5"
            : "mt-5 grid gap-5 sm:grid-cols-[minmax(0,13rem)_minmax(0,1fr)] sm:items-center"
        }
      >
        <img
          src={src}
          alt={alt}
          width={600}
          height={1230}
          loading="lazy"
          decoding="async"
          className={`mx-auto max-w-full drop-shadow-[0_18px_34px_rgba(20,17,13,0.30)] ${
            stacked ? "w-[14rem]" : "w-[13rem] sm:mx-0"
          }`}
        />
        <div className={stacked ? "mt-6" : undefined}>
          <p className="text-sm leading-relaxed text-brand-ink-soft">
            {lede ??
              "The calculator stops at the card name. This is the year built on it — the chapter you\u2019re standing in today, the six still coming, and what each one asks."}
          </p>
          {stacked ? null : (
            <ul className="mt-4 space-y-1.5 text-sm leading-relaxed text-brand-ink">
              {POINTS.map((point) => (
                <li key={point} className="flex gap-2">
                  <span aria-hidden="true" className="text-brand-bronze">
                    &middot;
                  </span>
                  {point}
                </li>
              ))}
            </ul>
          )}
          <Link
            href={DEEP_DIVE_PRODUCT_PATH}
            onClick={() =>
              trackClientFunnelEvent("offer_cta_clicked", {
                offerSlug: DEEP_DIVE_OFFER_SLUG,
                placement,
              })
            }
            className="mt-4 inline-block text-sm font-medium text-brand-ink underline underline-offset-4"
          >
            See your own year free &rarr;
          </Link>
          <p className="mt-2 text-xs leading-relaxed text-brand-ink-soft">
            {DEEP_DIVE_PRICE_LABEL} one time &middot; instant &middot; 12 months
            of access
          </p>
        </div>
      </div>
    </aside>
  );
}
